//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLogsView
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public string PlaceName { get; set; }
        public string Text { get; set; }
        public string AdditionalText { get; set; }
        public int Type { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeMiddleName { get; set; }
        public string IpAddress { get; set; }
        public string EmployeeLogin { get; set; }
    }
}
