//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public System.Guid Id { get; set; }
        public string Text { get; set; }
        public Nullable<int> Type { get; set; }
        public string AuthorId { get; set; }
        public string AuthorValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public string ExecutorsId { get; set; }
        public string ExecutorsValue { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public string DocumentValue { get; set; }
        public bool IsParrent { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> ParentTask { get; set; }
        public string ResponsibleId { get; set; }
        public string ResponsibleValue { get; set; }
        public bool IsNotActive { get; set; }
        public bool IsCurrent { get; set; }
        public string ModifiedUser { get; set; }
        public bool IsMainLine { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int TypeEx { get; set; }
        public int Branch { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
