//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ConnectionString { get; set; }
        public string DbName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsCurrent { get; set; }
        public string Owner { get; set; }
        public string Path { get; set; }
    }
}
