//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionDrugDosage
    {
        public int Id { get; set; }
        public int CommissionId { get; set; }
        public Nullable<int> ConclusionTypeId { get; set; }
        public string ConclusionComment { get; set; }
        public long DrugDosageId { get; set; }
        public System.Guid StageId { get; set; }
        public Nullable<int> ExpertResultId { get; set; }
    
        public virtual CommissionConclusionType CommissionConclusionType { get; set; }
        public virtual Commission Commission { get; set; }
        public virtual EXP_DrugDosage EXP_DrugDosage { get; set; }
        public virtual EXP_ExpertiseStageDosageResult EXP_ExpertiseStageDosageResult { get; set; }
        public virtual EXP_ExpertiseStage EXP_ExpertiseStage { get; set; }
    }
}
