//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionsView
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public string FullNumber { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsComplete { get; set; }
        public string Comment { get; set; }
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public int KindId { get; set; }
        public string KindName { get; set; }
        public string KindShortName { get; set; }
    }
}
