//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionConclusionType
    {
        public CommissionConclusionType()
        {
            this.CommissionDrugDosages = new HashSet<CommissionDrugDosage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CommissionType { get; set; }
        public Nullable<int> Code { get; set; }
        public string Name2 { get; set; }
    
        public virtual ICollection<CommissionDrugDosage> CommissionDrugDosages { get; set; }
    }
}
