//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionDrugDosageCount2View
    {
        public int CommissionId { get; set; }
        public Nullable<int> ConclusionTypeId { get; set; }
        public int IsRepeat { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
