//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionDrugDosageNeedCommission
    {
        public int Id { get; set; }
        public long DrugDosageId { get; set; }
        public System.Guid StageId { get; set; }
        public bool IsNeedEs { get; set; }
        public bool IsNeedFmk { get; set; }
        public bool IsNeedFmc { get; set; }
    
        public virtual EXP_DrugDosage EXP_DrugDosage { get; set; }
        public virtual EXP_ExpertiseStage EXP_ExpertiseStage { get; set; }
    }
}
