//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        public Commission()
        {
            this.CommissionQuestions = new HashSet<CommissionQuestion>();
            this.CommissionUnits = new HashSet<CommissionUnit>();
            this.EXP_ExpertiseStageDosageResult = new HashSet<EXP_ExpertiseStageDosageResult>();
            this.CommissionDrugDosages = new HashSet<CommissionDrugDosage>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public string FullNumber { get; set; }
        public int KindId { get; set; }
        public int TypeId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsComplete { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsNeedSendTimeOverNotifications { get; set; }
    
        public virtual CommissionKind CommissionKind { get; set; }
        public virtual ICollection<CommissionQuestion> CommissionQuestions { get; set; }
        public virtual CommissionType CommissionType { get; set; }
        public virtual ICollection<CommissionUnit> CommissionUnits { get; set; }
        public virtual ICollection<EXP_ExpertiseStageDosageResult> EXP_ExpertiseStageDosageResult { get; set; }
        public virtual ICollection<CommissionDrugDosage> CommissionDrugDosages { get; set; }
    }
}
