//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionQuestion
    {
        public int Id { get; set; }
        public int CommissionId { get; set; }
        public int Number { get; set; }
        public int TypeId { get; set; }
        public string Comment { get; set; }
    
        public virtual CommissionQuestionType CommissionQuestionType { get; set; }
        public virtual Commission Commission { get; set; }
    }
}
