//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositionsView
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> MaterialTypeDicId { get; set; }
        public Nullable<System.Guid> MaterialNameDicId { get; set; }
        public string MaterialName { get; set; }
        public decimal Count { get; set; }
        public string NormativeDocument { get; set; }
        public Nullable<System.Guid> CountryDicId { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public bool IsControl { get; set; }
        public bool IsPoison { get; set; }
        public Nullable<System.Guid> MaterialGainDicId { get; set; }
        public string MaterialGain { get; set; }
        public Nullable<System.Guid> MaterialOriginDicId { get; set; }
        public string MaterialTypeName { get; set; }
        public string Name { get; set; }
        public string CountryName { get; set; }
        public string MaterialGainName { get; set; }
        public string MaterialOriginName { get; set; }
        public Nullable<System.Guid> ObjectId { get; set; }
    }
}
