//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ManufacturerOrganizationId { get; set; }
        public Nullable<System.Guid> ApplicantOrganizationId { get; set; }
        public Nullable<System.Guid> DoverennostTypeDicId { get; set; }
        public string DoverennostNumber { get; set; }
        public Nullable<System.DateTime> DoverennostCreatedDate { get; set; }
        public Nullable<System.DateTime> DoverennostExpiryDate { get; set; }
        public Nullable<System.Guid> HolderOrganizationId { get; set; }
        public Nullable<System.Guid> PayerOrganizationId { get; set; }
        public string Number { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<bool> IsSite { get; set; }
        public bool IsHasDoverennostNumber { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public Nullable<System.Guid> PayerTranslationOrganizationId { get; set; }
        public Nullable<System.Guid> SignerId { get; set; }
        public Nullable<System.Guid> ContractAdditionTypeId { get; set; }
        public Nullable<System.Guid> HolderTypeId { get; set; }
    
        public virtual Dictionary ContractStatus { get; set; }
        public virtual Organization ManufacturerOrganization { get; set; }
        public virtual Organization PayerTranslationOrganization { get; set; }
        public virtual Organization ApplicantOrganization { get; set; }
        public virtual Organization HolderOrganization { get; set; }
        public virtual Organization PayerOrganization { get; set; }
        public virtual Employee Signer { get; set; }
        public virtual Dictionary ContractAdditionType { get; set; }
        public virtual Contract ParentContract { get; set; }
        public virtual Dictionary DoverennostType { get; set; }
        public virtual Dictionary HolderType { get; set; }
    }
}
