//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAdditionJournal
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ManufacturerOrganizationId { get; set; }
        public Nullable<System.Guid> ApplicantOrganizationId { get; set; }
        public Nullable<System.Guid> DoverennostTypeDicId { get; set; }
        public string DoverennostNumber { get; set; }
        public Nullable<System.DateTime> DoverennostCreatedDate { get; set; }
        public Nullable<System.DateTime> DoverennostExpiryDate { get; set; }
        public Nullable<System.Guid> HolderOrganizationId { get; set; }
        public Nullable<System.Guid> PayerOrganizationId { get; set; }
        public string Number { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<bool> IsSite { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerCountry { get; set; }
        public string ApplicantCountry { get; set; }
        public string ApplicantCurrency { get; set; }
        public string Login { get; set; }
        public string DocumentTypeName { get; set; }
        public string StatusName { get; set; }
        public string StatusCode { get; set; }
        public string HolderName { get; set; }
        public string ApplicantName { get; set; }
        public string PayerName { get; set; }
        public string CorrespondentsId { get; set; }
        public string CorrespondentsValue { get; set; }
        public string ExecutorId { get; set; }
        public Nullable<int> CountApplications { get; set; }
        public string ContractAdditionType { get; set; }
        public Nullable<System.Guid> SignerId { get; set; }
    }
}
