//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractComment
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Comment { get; set; }
        public System.Guid AuthorId { get; set; }
        public System.Guid ContractId { get; set; }
        public bool Sended { get; set; }
    
        public virtual Employee Author { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
