//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractSignedData
    {
        public System.Guid ContractId { get; set; }
        public string ApplicantSig { get; set; }
        public string CeoSign { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
