//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsView
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ManufacturerOrganizationId { get; set; }
        public Nullable<System.Guid> ApplicantOrganizationId { get; set; }
        public Nullable<System.Guid> DoverennostTypeDicId { get; set; }
        public string DoverennostNumber { get; set; }
        public Nullable<System.DateTime> DoverennostCreatedDate { get; set; }
        public Nullable<System.DateTime> DoverennostExpiryDate { get; set; }
        public Nullable<System.Guid> HolderOrganizationId { get; set; }
        public Nullable<System.Guid> PayerOrganizationId { get; set; }
        public string Number { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public string ManufactureOrgName { get; set; }
        public string ApplicantOrgName { get; set; }
        public string HolderOrgName { get; set; }
        public string PayerOrgName { get; set; }
        public string DoverenostName { get; set; }
        public Nullable<int> Type { get; set; }
        public string StatusName { get; set; }
        public bool IsHasDoverennostNumber { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<bool> IsSite { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.Guid> PayerTranslationOrganizationId { get; set; }
        public string PayerTranslationOrgName { get; set; }
        public Nullable<System.Guid> ContractAdditionTypeId { get; set; }
        public string ContractAdditionTypeName { get; set; }
    }
}
