//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_Storages
    {
        public DIC_Storages()
        {
            this.DIC_Storages1 = new HashSet<DIC_Storages>();
            this.EXP_Materials = new HashSet<EXP_Materials>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public string NameEn { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid OrganizationId { get; set; }
    
        public virtual ICollection<DIC_Storages> DIC_Storages1 { get; set; }
        public virtual DIC_Storages DIC_Storages2 { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<EXP_Materials> EXP_Materials { get; set; }
    }
}
