//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public Dictionary()
        {
            this.Dictionaries1 = new HashSet<Dictionary>();
            this.EXP_DrugCorespondence = new HashSet<EXP_DrugCorespondence>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string ExpireDate { get; set; }
        public string Year { get; set; }
        public string Note { get; set; }
        public string DepartmentsId { get; set; }
        public string DepartmentsValue { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string DisplayName { get; set; }
        public string EmployeesValue { get; set; }
        public string EmployeesId { get; set; }
        public string NameKz { get; set; }
        public bool IsGuide { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
    
        public virtual ICollection<Dictionary> Dictionaries1 { get; set; }
        public virtual Dictionary Dictionary1 { get; set; }
        public virtual ICollection<EXP_DrugCorespondence> EXP_DrugCorespondence { get; set; }
    }
}
