//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ncelsEntities : DbContext
    {
        public ncelsEntities()
            : base("name=ncelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessDocument> AccessDocuments { get; set; }
        public DbSet<AccessTask> AccessTasks { get; set; }
        public DbSet<Activity> Activities { get; set; }
        public DbSet<Archive> Archives { get; set; }
        public DbSet<Dictionary> Dictionaries { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<EmployeePermission> EmployeePermissions { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Experience> Experiences { get; set; }
        public DbSet<ExtensionExecution> ExtensionExecutions { get; set; }
        public DbSet<History> Histories { get; set; }
        public DbSet<Holiday> Holidays { get; set; }
        public DbSet<LinkDocument> LinkDocuments { get; set; }
        public DbSet<LinkUnit> LinkUnits { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<PermissionKey> PermissionKeys { get; set; }
        public DbSet<PermissionValue> PermissionValues { get; set; }
        public DbSet<PrismEnum> PrismEnums { get; set; }
        public DbSet<PrismReport> PrismReports { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<Template> Templates { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<LinkDictionary> LinkDictionaries { get; set; }
        public DbSet<AdministrativeDocument> AdministrativeDocuments { get; set; }
        public DbSet<ArchivView> ArchivViews { get; set; }
        public DbSet<CitizenDocument> CitizenDocuments { get; set; }
        public DbSet<CorrespondenceDocument> CorrespondenceDocuments { get; set; }
        public DbSet<IncomingDocument> IncomingDocuments { get; set; }
        public DbSet<OutgoingDocument> OutgoingDocuments { get; set; }
        public DbSet<ProjectDocument> ProjectDocuments { get; set; }
        public DbSet<Registery> Registeries { get; set; }
        public DbSet<Change> Changes { get; set; }
        public DbSet<Composition> Compositions { get; set; }
        public DbSet<Contract> Contracts { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<Package> Packages { get; set; }
        public DbSet<PriceProject> PriceProjects { get; set; }
        public DbSet<RegisterProject> RegisterProjects { get; set; }
        public DbSet<OrganizationsView> OrganizationsViews { get; set; }
        public DbSet<RegisterProjectsView> RegisterProjectsViews { get; set; }
        public DbSet<PriceProjectsView> PriceProjectsViews { get; set; }
        public DbSet<PricesView> PricesViews { get; set; }
        public DbSet<ProjectsView> ProjectsViews { get; set; }
        public DbSet<PackagesView> PackagesViews { get; set; }
        public DbSet<CompositionsView> CompositionsViews { get; set; }
        public DbSet<RegisterProjectJournal> RegisterProjectJournals { get; set; }
        public DbSet<ContractsView> ContractsViews { get; set; }
        public DbSet<Ref_PurchasePrices> Ref_PurchasePrices { get; set; }
        public DbSet<TmcOff> TmcOffs { get; set; }
        public DbSet<TmcOut> TmcOuts { get; set; }
        public DbSet<TmcOutCount> TmcOutCounts { get; set; }
        public DbSet<TmcOffView> TmcOffViews { get; set; }
        public DbSet<TmcView> TmcViews { get; set; }
        public DbSet<Installation> Installations { get; set; }
        public DbSet<OrphanDrugsIcdDeseasesView> OrphanDrugsIcdDeseasesViews { get; set; }
        public DbSet<Ref_Limits> Ref_Limits { get; set; }
        public DbSet<PrtPrj> PrtPrjs { get; set; }
        public DbSet<PrtPrjsView> PrtPrjsViews { get; set; }
        public DbSet<PrtPrjsView2> PrtPrjsView2 { get; set; }
        public DbSet<PriceListExpertise> PriceListExpertises { get; set; }
        public DbSet<TmcOutView> TmcOutViews { get; set; }
        public DbSet<TmcApplicationComment> TmcApplicationComments { get; set; }
        public DbSet<Ref_Knfs> Ref_Knfs { get; set; }
        public DbSet<obk_currencies> obk_currencies { get; set; }
        public DbSet<obk_exchangerate> obk_exchangerate { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<obk_product_cost> obk_product_cost { get; set; }
        public DbSet<obk_products> obk_products { get; set; }
        public DbSet<Ref_MarketPrices> Ref_MarketPrices { get; set; }
        public DbSet<TmcIn> TmcIns { get; set; }
        public DbSet<Tmc> Tmcs { get; set; }
        public DbSet<ReesrtObk> ReesrtObks { get; set; }
        public DbSet<TmcInView> TmcInViews { get; set; }
        public DbSet<RequestList> RequestLists { get; set; }
        public DbSet<RegisterOrdererView> RegisterOrdererViews { get; set; }
        public DbSet<sr_register_mt_parts> sr_register_mt_parts { get; set; }
        public DbSet<RequestListView> RequestListViews { get; set; }
        public DbSet<SignDocument> SignDocuments { get; set; }
        public DbSet<TmcReport> TmcReports { get; set; }
        public DbSet<TmcReportTask> TmcReportTasks { get; set; }
        public DbSet<TmcReportsView> TmcReportsViews { get; set; }
        public DbSet<TmcOutCountView> TmcOutCountViews { get; set; }
        public DbSet<EXP_DIC_AccelerationType> EXP_DIC_AccelerationType { get; set; }
        public DbSet<EXP_DIC_DrugType> EXP_DIC_DrugType { get; set; }
        public DbSet<EXP_DIC_ManufactureType> EXP_DIC_ManufactureType { get; set; }
        public DbSet<EXP_DIC_Origin> EXP_DIC_Origin { get; set; }
        public DbSet<EXP_DIC_PeriodMeasure> EXP_DIC_PeriodMeasure { get; set; }
        public DbSet<EXP_DIC_PlantKind> EXP_DIC_PlantKind { get; set; }
        public DbSet<EXP_DIC_SaleType> EXP_DIC_SaleType { get; set; }
        public DbSet<EXP_DIC_Status> EXP_DIC_Status { get; set; }
        public DbSet<EXP_DIC_Type> EXP_DIC_Type { get; set; }
        public DbSet<EXP_DIC_WrappingType> EXP_DIC_WrappingType { get; set; }
        public DbSet<EXP_DrugDeclaration> EXP_DrugDeclaration { get; set; }
        public DbSet<EXP_DrugDeclarationCom> EXP_DrugDeclarationCom { get; set; }
        public DbSet<EXP_DrugDeclarationComRecord> EXP_DrugDeclarationComRecord { get; set; }
        public DbSet<EXP_DrugDeclarationFieldHistory> EXP_DrugDeclarationFieldHistory { get; set; }
        public DbSet<EXP_DrugDeclarationHistory> EXP_DrugDeclarationHistory { get; set; }
        public DbSet<EXP_DrugExportTrade> EXP_DrugExportTrade { get; set; }
        public DbSet<EXP_DrugPatent> EXP_DrugPatent { get; set; }
        public DbSet<EXP_DrugSubstance> EXP_DrugSubstance { get; set; }
        public DbSet<EXP_DrugType> EXP_DrugType { get; set; }
        public DbSet<EXP_DrugUseMethod> EXP_DrugUseMethod { get; set; }
        public DbSet<EXP_DrugWrapping> EXP_DrugWrapping { get; set; }
        public DbSet<sr_atc_codes> sr_atc_codes { get; set; }
        public DbSet<sr_boxes> sr_boxes { get; set; }
        public DbSet<sr_categories> sr_categories { get; set; }
        public DbSet<sr_countries> sr_countries { get; set; }
        public DbSet<sr_dosage_forms> sr_dosage_forms { get; set; }
        public DbSet<sr_drug_forms> sr_drug_forms { get; set; }
        public DbSet<sr_international_names> sr_international_names { get; set; }
        public DbSet<sr_measures> sr_measures { get; set; }
        public DbSet<sr_substances> sr_substances { get; set; }
        public DbSet<sr_use_methods> sr_use_methods { get; set; }
        public DbSet<sr_substance_types> sr_substance_types { get; set; }
        public DbSet<EXP_DrugDeclarationView> EXP_DrugDeclarationView { get; set; }
        public DbSet<FileLink> FileLinks { get; set; }
        public DbSet<EXP_DIC_DrugTypeKind> EXP_DIC_DrugTypeKind { get; set; }
        public DbSet<EXP_DrugOtherCountry> EXP_DrugOtherCountry { get; set; }
        public DbSet<EXP_DrugProtectionDoc> EXP_DrugProtectionDoc { get; set; }
        public DbSet<EXP_DrugOrganizations> EXP_DrugOrganizations { get; set; }
        public DbSet<EXP_DrugPrice> EXP_DrugPrice { get; set; }
        public DbSet<EXP_DirectionToPays> EXP_DirectionToPays { get; set; }
        public DbSet<EXP_DrugDeclarationDirectionToPayView> EXP_DrugDeclarationDirectionToPayView { get; set; }
        public DbSet<EXP_PriceListDirectionToPayView> EXP_PriceListDirectionToPayView { get; set; }
        public DbSet<ContractProcSetting> ContractProcSettings { get; set; }
        public DbSet<ContractAdditionJournal> ContractAdditionJournals { get; set; }
        public DbSet<ContractJournal> ContractJournals { get; set; }
        public DbSet<EXP_Tasks> EXP_Tasks { get; set; }
        public DbSet<EXP_Activities> EXP_Activities { get; set; }
        public DbSet<EXP_AgreementProcSettings> EXP_AgreementProcSettings { get; set; }
        public DbSet<EXP_AgreementProcSettingsActivities> EXP_AgreementProcSettingsActivities { get; set; }
        public DbSet<EXP_AgreementProcSettingsTasks> EXP_AgreementProcSettingsTasks { get; set; }
        public DbSet<ContractComment> ContractComments { get; set; }
        public DbSet<EXP_DrugDosage> EXP_DrugDosage { get; set; }
        public DbSet<EXP_DirectionToPaysView> EXP_DirectionToPaysView { get; set; }
        public DbSet<FileLinkView> FileLinkViews { get; set; }
        public DbSet<EXP_DIC_PrimaryMark> EXP_DIC_PrimaryMark { get; set; }
        public DbSet<EXP_DIC_RemarkType> EXP_DIC_RemarkType { get; set; }
        public DbSet<EXP_DrugAppDosageRemark> EXP_DrugAppDosageRemark { get; set; }
        public DbSet<EXP_DrugAppDosageResult> EXP_DrugAppDosageResult { get; set; }
        public DbSet<EXP_DrugPrimaryKind> EXP_DrugPrimaryKind { get; set; }
        public DbSet<sr_register> sr_register { get; set; }
        public DbSet<sr_register_drugs> sr_register_drugs { get; set; }
        public DbSet<EXP_DIC_ChangeType> EXP_DIC_ChangeType { get; set; }
        public DbSet<EXP_DrugChangeType> EXP_DrugChangeType { get; set; }
        public DbSet<I1c_exp_Contracts> I1c_exp_Contracts { get; set; }
        public DbSet<sr_producers> sr_producers { get; set; }
        public DbSet<SrProducerView> SrProducerViews { get; set; }
        public DbSet<RegisterOrderer2Views> RegisterOrderer2Views { get; set; }
        public DbSet<EXP_PriceListDrugTypeMapping> EXP_PriceListDrugTypeMapping { get; set; }
        public DbSet<EXP_DirectionToPays_PriceList> EXP_DirectionToPays_PriceList { get; set; }
        public DbSet<EXP_PriceList> EXP_PriceList { get; set; }
        public DbSet<FileLinksCategoryCom> FileLinksCategoryComs { get; set; }
        public DbSet<FileLinksCategoryComRecord> FileLinksCategoryComRecords { get; set; }
        public DbSet<ContractSignedData> ContractSignedDatas { get; set; }
        public DbSet<DIC_Storages> DIC_Storages { get; set; }
        public DbSet<EXP_DIC_TypeFileND> EXP_DIC_TypeFileND { get; set; }
        public DbSet<EXP_DIC_TypeND> EXP_DIC_TypeND { get; set; }
        public DbSet<EXP_DrugPrimaryNTD> EXP_DrugPrimaryNTD { get; set; }
        public DbSet<EmployeePermissionRole> EmployeePermissionRoles { get; set; }
        public DbSet<PermissionRole> PermissionRoles { get; set; }
        public DbSet<PermissionRoleKey> PermissionRoleKeys { get; set; }
        public DbSet<EXP_DIC_NormDocFarm> EXP_DIC_NormDocFarm { get; set; }
        public DbSet<sr_register_boxes> sr_register_boxes { get; set; }
        public DbSet<sr_register_substances> sr_register_substances { get; set; }
        public DbSet<sr_register_use_methods> sr_register_use_methods { get; set; }
        public DbSet<GridSetting> GridSettings { get; set; }
        public DbSet<EXP_DrugDeclarationRegisterView> EXP_DrugDeclarationRegisterView { get; set; }
        public DbSet<PriceRejectProject> PriceRejectProjects { get; set; }
        public DbSet<PriceProjectCom> PriceProjectComs { get; set; }
        public DbSet<PriceProjectComRecord> PriceProjectComRecords { get; set; }
        public DbSet<PriceProjectFieldHistory> PriceProjectFieldHistories { get; set; }
        public DbSet<VisitEmployeeType> VisitEmployeeTypes { get; set; }
        public DbSet<VisitEmployeeWorkingTime> VisitEmployeeWorkingTimes { get; set; }
        public DbSet<Visit> Visits { get; set; }
        public DbSet<VisitStatus> VisitStatuses { get; set; }
        public DbSet<VisitType> VisitTypes { get; set; }
        public DbSet<VisitsView> VisitsViews { get; set; }
        public DbSet<EXP_DIC_PrimaryOTD> EXP_DIC_PrimaryOTD { get; set; }
        public DbSet<EXP_DrugPrimaryRemark> EXP_DrugPrimaryRemark { get; set; }
        public DbSet<EXP_TaskRegistryView> EXP_TaskRegistryView { get; set; }
        public DbSet<EXP_RegistrationExpSteps> EXP_RegistrationExpSteps { get; set; }
        public DbSet<EXP_RegistrationTypes> EXP_RegistrationTypes { get; set; }
        public DbSet<EXP_DrugPrimaryFinalDocument> EXP_DrugPrimaryFinalDocument { get; set; }
        public DbSet<CommissionKind> CommissionKinds { get; set; }
        public DbSet<CommissionUnit> CommissionUnits { get; set; }
        public DbSet<CommissionUnitType> CommissionUnitTypes { get; set; }
        public DbSet<CommissionsView> CommissionsViews { get; set; }
        public DbSet<EXP_DIC_CorespondenceKind> EXP_DIC_CorespondenceKind { get; set; }
        public DbSet<EXP_DIC_CorespondenceType> EXP_DIC_CorespondenceType { get; set; }
        public DbSet<EXP_DIC_PrimaryFinalyDocResult> EXP_DIC_PrimaryFinalyDocResult { get; set; }
        public DbSet<EXP_DIC_Stage> EXP_DIC_Stage { get; set; }
        public DbSet<EXP_DrugCorespondence> EXP_DrugCorespondence { get; set; }
        public DbSet<EXP_DrugCorespondenceRemark> EXP_DrugCorespondenceRemark { get; set; }
        public DbSet<CommissionQuestion> CommissionQuestions { get; set; }
        public DbSet<CommissionQuestionType> CommissionQuestionTypes { get; set; }
        public DbSet<EXP_DIC_StageResult> EXP_DIC_StageResult { get; set; }
        public DbSet<EXP_DIC_StageStatus> EXP_DIC_StageStatus { get; set; }
        public DbSet<EXP_ExpertisePrimaryFinalDoc> EXP_ExpertisePrimaryFinalDoc { get; set; }
        public DbSet<EXP_ExpertiseStage> EXP_ExpertiseStage { get; set; }
        public DbSet<EXP_ExpertiseStageDosage> EXP_ExpertiseStageDosage { get; set; }
        public DbSet<SrReestrView> SrReestrViews { get; set; }
        public DbSet<EXP_MaterialDirections> EXP_MaterialDirections { get; set; }
        public DbSet<EXP_MaterialDirectionsView> EXP_MaterialDirectionsView { get; set; }
        public DbSet<EXP_ExpertisePharmaceuticalFinalDoc> EXP_ExpertisePharmaceuticalFinalDoc { get; set; }
        public DbSet<EXP_ExpertisePharmacologicalFinalDoc> EXP_ExpertisePharmacologicalFinalDoc { get; set; }
        public DbSet<EXP_ExpertiseStageRemark> EXP_ExpertiseStageRemark { get; set; }
        public DbSet<EXP_ExpertiseSafetyreportFinalDoc> EXP_ExpertiseSafetyreportFinalDoc { get; set; }
        public DbSet<CommissionConclusionType> CommissionConclusionTypes { get; set; }
        public DbSet<Commission> Commissions { get; set; }
        public DbSet<CommissionType> CommissionTypes { get; set; }
        public DbSet<PriceProject_Ext> PriceProject_Ext { get; set; }
        public DbSet<PriceProjectArchiveView> PriceProjectArchiveViews { get; set; }
        public DbSet<EXP_DIC_AnalyseIndicator> EXP_DIC_AnalyseIndicator { get; set; }
        public DbSet<EXP_DrugAnaliseIndicator> EXP_DrugAnaliseIndicator { get; set; }
        public DbSet<PP_ProtocolComissionMembers> PP_ProtocolComissionMembers { get; set; }
        public DbSet<PP_ProtocolProductPrices> PP_ProtocolProductPrices { get; set; }
        public DbSet<PP_Protocols> PP_Protocols { get; set; }
        public DbSet<EXP_ExpertiseStageDosageCommissionView> EXP_ExpertiseStageDosageCommissionView { get; set; }
        public DbSet<ActionLog> ActionLogs { get; set; }
        public DbSet<ActionLogsView> ActionLogsViews { get; set; }
        public DbSet<sr_producer_types> sr_producer_types { get; set; }
        public DbSet<sr_register_producers> sr_register_producers { get; set; }
        public DbSet<DIC_FileLinkStatus> DIC_FileLinkStatus { get; set; }
        public DbSet<EXP_DIC_CorespondenceSubject> EXP_DIC_CorespondenceSubject { get; set; }
        public DbSet<EXP_CertificateOfCompletion> EXP_CertificateOfCompletion { get; set; }
        public DbSet<EXP_CertificateOfCompletionView> EXP_CertificateOfCompletionView { get; set; }
        public DbSet<PP_ProtocolListView> PP_ProtocolListView { get; set; }
        public DbSet<UniqueIdentificator> UniqueIdentificators { get; set; }
        public DbSet<EXP_DrugSubstanceManufacture> EXP_DrugSubstanceManufacture { get; set; }
        public DbSet<Price> Prices { get; set; }
        public DbSet<EXP_ExpertiseStageDosageResult> EXP_ExpertiseStageDosageResult { get; set; }
        public DbSet<CommissionDrugDosageNeedCommission> CommissionDrugDosageNeedCommissions { get; set; }
        public DbSet<Exp_DrugDosageStageForAddView> Exp_DrugDosageStageForAddView { get; set; }
        public DbSet<CommissionDrugDosage> CommissionDrugDosages { get; set; }
        public DbSet<PP_ProcessingJournal> PP_ProcessingJournal { get; set; }
        public DbSet<EXP_Materials> EXP_Materials { get; set; }
        public DbSet<RemarkType> RemarkTypes { get; set; }
        public DbSet<Exp_DrugDosageStageView> Exp_DrugDosageStageView { get; set; }
        public DbSet<PriceProjectsHistory> PriceProjectsHistories { get; set; }
        public DbSet<PriceProjectJournal> PriceProjectJournals { get; set; }
        public DbSet<I1c_lims_ContractProducts> I1c_lims_ContractProducts { get; set; }
        public DbSet<I1c_lims_Contracts> I1c_lims_Contracts { get; set; }
        public DbSet<RequestOrder> RequestOrders { get; set; }
        public DbSet<RequestOrderListView> RequestOrderListViews { get; set; }
        public DbSet<AvgExchangeRatesView> AvgExchangeRatesViews { get; set; }
    
        public virtual int CloseTask(Nullable<System.Guid> id, string note, string modifiedUser)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var modifiedUserParameter = modifiedUser != null ?
                new ObjectParameter("ModifiedUser", modifiedUser) :
                new ObjectParameter("ModifiedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CloseTask", idParameter, noteParameter, modifiedUserParameter);
        }
    
        public virtual int ActivityIsMainLine(Nullable<System.Guid> docId)
        {
            var docIdParameter = docId.HasValue ?
                new ObjectParameter("DocId", docId) :
                new ObjectParameter("DocId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActivityIsMainLine", docIdParameter);
        }
    }
}
