//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_ExpertiseStageDosage
    {
        public EXP_ExpertiseStageDosage()
        {
            this.PrimaryFinalDocs = new HashSet<EXP_ExpertisePrimaryFinalDoc>();
            this.EXP_ExpertisePharmaceuticalFinalDoc = new HashSet<EXP_ExpertisePharmaceuticalFinalDoc>();
            this.EXP_ExpertisePharmacologicalFinalDoc = new HashSet<EXP_ExpertisePharmacologicalFinalDoc>();
            this.EXP_ExpertiseSafetyreportFinalDoc = new HashSet<EXP_ExpertiseSafetyreportFinalDoc>();
            this.EXP_DrugAnaliseIndicator = new HashSet<EXP_DrugAnaliseIndicator>();
            this.EXP_ExpertiseStageDosageResult = new HashSet<EXP_ExpertiseStageDosageResult>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid StageId { get; set; }
        public long DosageId { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<System.Guid> FinalDocStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Dictionary FinalDocStatus { get; set; }
        public virtual EXP_DIC_StageResult EXP_DIC_StageResult { get; set; }
        public virtual EXP_DrugDosage EXP_DrugDosage { get; set; }
        public virtual ICollection<EXP_ExpertisePrimaryFinalDoc> PrimaryFinalDocs { get; set; }
        public virtual EXP_ExpertiseStage EXP_ExpertiseStage { get; set; }
        public virtual ICollection<EXP_ExpertisePharmaceuticalFinalDoc> EXP_ExpertisePharmaceuticalFinalDoc { get; set; }
        public virtual ICollection<EXP_ExpertisePharmacologicalFinalDoc> EXP_ExpertisePharmacologicalFinalDoc { get; set; }
        public virtual ICollection<EXP_ExpertiseSafetyreportFinalDoc> EXP_ExpertiseSafetyreportFinalDoc { get; set; }
        public virtual ICollection<EXP_DrugAnaliseIndicator> EXP_DrugAnaliseIndicator { get; set; }
        public virtual ICollection<EXP_ExpertiseStageDosageResult> EXP_ExpertiseStageDosageResult { get; set; }
    }
}
