//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugDeclarationCom
    {
        public EXP_DrugDeclarationCom()
        {
            this.EXP_DrugDeclarationComRecord = new HashSet<EXP_DrugDeclarationComRecord>();
        }
    
        public long Id { get; set; }
        public System.Guid DrugDeclarationId { get; set; }
        public bool IsError { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsDelete { get; set; }
        public string ControlId { get; set; }
    
        public virtual EXP_DrugDeclaration EXP_DrugDeclaration { get; set; }
        public virtual ICollection<EXP_DrugDeclarationComRecord> EXP_DrugDeclarationComRecord { get; set; }
    }
}
