//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugAppDosageResult
    {
        public long Id { get; set; }
        public string NameResult { get; set; }
        public bool IsMark { get; set; }
        public Nullable<int> RemarkTypeId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> RemarkDate { get; set; }
        public Nullable<System.DateTime> FixedDate { get; set; }
        public long DrugDosageId { get; set; }
    
        public virtual EXP_DIC_RemarkType EXP_DIC_RemarkType { get; set; }
        public virtual EXP_DrugDosage EXP_DrugDosage { get; set; }
    }
}
