//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_Tasks
    {
        public EXP_Tasks()
        {
            this.EXP_TasksChild = new HashSet<EXP_Tasks>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TypeId { get; set; }
        public string TypeValue { get; set; }
        public System.Guid StatusId { get; set; }
        public string StatusValue { get; set; }
        public int OrderNumber { get; set; }
        public string Number { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ExecutedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public System.Guid AuthorId { get; set; }
        public string AuthorValue { get; set; }
        public System.Guid ExecutorId { get; set; }
        public string ExecutorValue { get; set; }
        public System.Guid ActivityId { get; set; }
        public Nullable<System.Guid> ParentTaskId { get; set; }
        public string Comment { get; set; }
        public string DigSign { get; set; }
    
        public virtual Dictionary ExpTaskType { get; set; }
        public virtual Dictionary StatusesDictionary { get; set; }
        public virtual Employee AuthorEmployee { get; set; }
        public virtual Employee ExecutorEmployee { get; set; }
        public virtual ICollection<EXP_Tasks> EXP_TasksChild { get; set; }
        public virtual EXP_Tasks EXP_TaskParent { get; set; }
        public virtual EXP_Activities EXP_Activities { get; set; }
    }
}
