//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_RegistrationExpSteps
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int Duration { get; set; }
        public System.Guid RegistrationId { get; set; }
        public int Priority { get; set; }
    
        public virtual EXP_RegistrationTypes EXP_RegistrationTypes { get; set; }
    }
}
