//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_ExpertiseStageDosageResult
    {
        public EXP_ExpertiseStageDosageResult()
        {
            this.CommissionDrugDosages = new HashSet<CommissionDrugDosage>();
        }
    
        public int Id { get; set; }
        public System.Guid StageDosageId { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<System.Guid> ResultCreatorId { get; set; }
        public Nullable<int> CommissionId { get; set; }
    
        public virtual Commission Commission { get; set; }
        public virtual EXP_DIC_StageResult EXP_DIC_StageResult { get; set; }
        public virtual EXP_ExpertiseStageDosage EXP_ExpertiseStageDosage { get; set; }
        public virtual ICollection<CommissionDrugDosage> CommissionDrugDosages { get; set; }
    }
}
