//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_AgreementProcSettingsActivities
    {
        public EXP_AgreementProcSettingsActivities()
        {
            this.EXP_AgreementProcSettingsTasks = new HashSet<EXP_AgreementProcSettingsTasks>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid SettingId { get; set; }
        public System.Guid ActivityTypeId { get; set; }
    
        public virtual Dictionary ActivityType { get; set; }
        public virtual EXP_AgreementProcSettings Setting { get; set; }
        public virtual ICollection<EXP_AgreementProcSettingsTasks> EXP_AgreementProcSettingsTasks { get; set; }
    }
}
