//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_AgreementProcSettingsTasks
    {
        public EXP_AgreementProcSettingsTasks()
        {
            this.EXP_AgreementProcSettingsTasks1 = new HashSet<EXP_AgreementProcSettingsTasks>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ActivityId { get; set; }
        public System.Guid TaskTypeId { get; set; }
        public Nullable<System.Guid> ParentTaskId { get; set; }
        public Nullable<System.Guid> ExecutorId { get; set; }
        public int OrderNum { get; set; }
    
        public virtual Dictionary TaskType { get; set; }
        public virtual Employee Executor { get; set; }
        public virtual EXP_AgreementProcSettingsActivities EXP_AgreementProcSettingsActivities { get; set; }
        public virtual ICollection<EXP_AgreementProcSettingsTasks> EXP_AgreementProcSettingsTasks1 { get; set; }
        public virtual EXP_AgreementProcSettingsTasks ParentTask { get; set; }
    }
}
