//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_MaterialDirectionsView
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string Number { get; set; }
        public System.Guid DrugDeclarationId { get; set; }
        public int StatusId { get; set; }
        public string StatusStr { get; set; }
        public string StatusKzStr { get; set; }
        public Nullable<System.Guid> SendEmployeeId { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.Guid> ExecutorEmployeeId { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public string Comment { get; set; }
        public string DdNumber { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public string RegistrationTypeRu { get; set; }
        public string RegistrationTypeKz { get; set; }
        public string TradeNameRu { get; set; }
        public string TradeNameKz { get; set; }
        public string TradeNameEn { get; set; }
        public decimal Dosage { get; set; }
        public Nullable<long> DosageMeasureTypeId { get; set; }
        public string DosageMeasureTypeName { get; set; }
        public string ConcentrationRu { get; set; }
        public string ConcentrationKz { get; set; }
        public string DrugFormName { get; set; }
        public string DrugFormNameKz { get; set; }
        public string DrugTypeNameRu { get; set; }
        public string DrugTypeNameKz { get; set; }
        public string ProducerNameRu { get; set; }
        public string ProducerNameKz { get; set; }
        public string ProducerNameEn { get; set; }
        public string CountryName { get; set; }
        public string CountryNameKz { get; set; }
        public string StatusCode { get; set; }
    }
}
