//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugSubstanceView
    {
        public System.Guid DrugDeclarationId { get; set; }
        public string ActiveSubstanceRu { get; set; }
        public string ActiveSubstanceKz { get; set; }
        public string SecondarySubstanceRu { get; set; }
        public string SecondarySubstanceKz { get; set; }
    }
}
