//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_ExpertiseSafetyreportFinalDoc
    {
        public System.Guid Id { get; set; }
        public string Conclusion { get; set; }
        public System.Guid DosageStageId { get; set; }
        public string PrimaryConclusion { get; set; }
        public string PharmaceuticalConclusion { get; set; }
        public string PharmacologicalConclusion { get; set; }
        public string AnalyticalConclusion { get; set; }
        public string PrimaryConclusionKz { get; set; }
        public string PharmaceuticalConclusionKz { get; set; }
        public string PharmacologicalConclusionKz { get; set; }
        public string AnalyticalConclusionKz { get; set; }
        public string ConclusionKz { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsAcceptedKz { get; set; }
        public string RemarkKz { get; set; }
    
        public virtual EXP_ExpertiseStageDosage EXP_ExpertiseStageDosage { get; set; }
    }
}
