//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugDeclarationRegisterView
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public int TypeId { get; set; }
        public string TypeNameRu { get; set; }
        public string TypeNameKz { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public string NameEn { get; set; }
        public Nullable<System.DateTime> FirstSendDate { get; set; }
        public string ProducerRu { get; set; }
        public string ProducerKz { get; set; }
        public string ProducerEn { get; set; }
        public string PackerRu { get; set; }
        public string PackerKz { get; set; }
        public string PackerEn { get; set; }
        public string ReleaseControlRu { get; set; }
        public string ReleaseControlKz { get; set; }
        public string ReleaseControlEn { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string CountryRu { get; set; }
        public string CountryKz { get; set; }
        public int StatusId { get; set; }
        public string StatusRu { get; set; }
        public string StatusKz { get; set; }
        public string DrugTypeRu { get; set; }
        public string DrugTypeKz { get; set; }
        public Nullable<int> MnnId { get; set; }
        public string MnnRu { get; set; }
        public string MnnKz { get; set; }
        public string MnnEn { get; set; }
        public string DrugFormRu { get; set; }
        public string DrugFormKz { get; set; }
        public string DosageRu { get; set; }
        public string DosageKz { get; set; }
        public System.Guid StageId { get; set; }
        public string StageRu { get; set; }
        public string StageKz { get; set; }
        public System.Guid ExpertId { get; set; }
        public string ExpertInitials { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public bool Paid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> OnBoard { get; set; }
        public Nullable<bool> ProductionEvaluation { get; set; }
        public Nullable<System.DateTime> StageStartDate { get; set; }
        public Nullable<System.DateTime> StageControlDate { get; set; }
        public Nullable<System.DateTime> ConclusionDate { get; set; }
        public Nullable<bool> StageCompleted { get; set; }
        public Nullable<System.DateTime> StageEndDate { get; set; }
        public Nullable<bool> StageOverdue { get; set; }
        public Nullable<int> OverdueDays { get; set; }
        public Nullable<System.Guid> LetterId { get; set; }
        public string LetterNumber { get; set; }
        public Nullable<int> StageDays { get; set; }
        public Nullable<bool> IsNewProducer { get; set; }
        public string ActiveSubstanceRu { get; set; }
        public string ActiveSubstanceKz { get; set; }
        public string SecondarySubstanceRu { get; set; }
        public string SecondarySubstanceKz { get; set; }
        public Nullable<int> CountDosageIsControl { get; set; }
        public string ApplicantRu { get; set; }
        public string ApplicantKz { get; set; }
        public string ApplicantEn { get; set; }
        public string ApplicantCountryRu { get; set; }
        public string ApplicantCountryKz { get; set; }
        public string HolderRu { get; set; }
        public string HolderKz { get; set; }
        public string HolderEn { get; set; }
        public string HolderCountryRu { get; set; }
        public string HolderCountryKz { get; set; }
        public string StatusCode { get; set; }
        public int DicStageId { get; set; }
        public string StageCode { get; set; }
        public string StageResultRu { get; set; }
        public string StageResultKz { get; set; }
        public Nullable<System.DateTime> SuspendedStartDate { get; set; }
        public Nullable<bool> PaymentOverdue { get; set; }
        public Nullable<int> SuspensionPeriod { get; set; }
        public string PaymentNumber { get; set; }
        public string InvoiceNumber1C { get; set; }
    }
}
