//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_Materials
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string Name { get; set; }
        public System.Guid TypeId { get; set; }
        public Nullable<int> DrugFormId { get; set; }
        public Nullable<decimal> Dosage { get; set; }
        public Nullable<System.Guid> DosageUnitId { get; set; }
        public Nullable<int> DosageQuantity { get; set; }
        public string Concentration { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<System.Guid> VolumeUnitId { get; set; }
        public bool IsContainNPP { get; set; }
        public Nullable<System.Guid> ProducerId { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public int Quantity { get; set; }
        public System.Guid UnitId { get; set; }
        public string Batch { get; set; }
        public Nullable<System.DateTime> DateOfManufacture { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> RetestDate { get; set; }
        public bool IsCertificatePassport { get; set; }
        public Nullable<System.Guid> StorageId { get; set; }
        public Nullable<decimal> StorageTemperatureFrom { get; set; }
        public Nullable<decimal> StorageTemperatureTo { get; set; }
        public Nullable<decimal> ActiveSubstancePercent { get; set; }
        public Nullable<decimal> WaterContentPercent { get; set; }
        public System.Guid DrugDeclarationId { get; set; }
        public bool IsAdditional { get; set; }
        public Nullable<System.Guid> StorageConditionId { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public Nullable<System.Guid> ExternalStateId { get; set; }
        public Nullable<System.Guid> ConcordanceStatementId { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<System.DateTime> ExpirationAfterOpeningDate { get; set; }
        public Nullable<System.Guid> ConcentrationUnitId { get; set; }
    
        public virtual DIC_Storages DIC_Storages { get; set; }
        public virtual Dictionary ConcentrationUnit { get; set; }
        public virtual Dictionary ConcordanceStatement { get; set; }
        public virtual Dictionary Country { get; set; }
        public virtual Dictionary DosageUnit { get; set; }
        public virtual Dictionary ExternalState { get; set; }
        public virtual Dictionary Status { get; set; }
        public virtual Dictionary StorageCondition { get; set; }
        public virtual Dictionary MaterialType { get; set; }
        public virtual Dictionary Unit { get; set; }
        public virtual Dictionary VolumeUnit { get; set; }
        public virtual EXP_DrugDeclaration EXP_DrugDeclaration { get; set; }
        public virtual Organization Producer { get; set; }
        public virtual sr_dosage_forms sr_dosage_forms { get; set; }
    }
}
