//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_PriceList
    {
        public EXP_PriceList()
        {
            this.EXP_DirectionToPays_PriceList = new HashSet<EXP_DirectionToPays_PriceList>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public string NameEn { get; set; }
        public Nullable<decimal> PriceRegisterForeign { get; set; }
        public Nullable<decimal> PriceRegisterForeignNds { get; set; }
        public Nullable<decimal> PriceReRegisterForeign { get; set; }
        public Nullable<decimal> PriceReRegisterForeignNds { get; set; }
        public Nullable<decimal> PriceRegisterKz { get; set; }
        public Nullable<decimal> PriceRegisterKzNds { get; set; }
        public Nullable<decimal> PriceReRegisterKz { get; set; }
        public Nullable<decimal> PriceReRegisterKzNds { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<EXP_DirectionToPays_PriceList> EXP_DirectionToPays_PriceList { get; set; }
    }
}
