//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugPrimaryKind
    {
        public long Id { get; set; }
        public System.Guid DrugDeclarationId { get; set; }
        public int PrimaryKindId { get; set; }
    
        public virtual EXP_DIC_PrimaryMark EXP_DIC_PrimaryMark { get; set; }
        public virtual EXP_DrugDeclaration EXP_DrugDeclaration { get; set; }
    }
}
