//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugCorespondence
    {
        public EXP_DrugCorespondence()
        {
            this.EXP_DrugCorespondenceRemark = new HashSet<EXP_DrugCorespondenceRemark>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid DrugDeclarationId { get; set; }
        public Nullable<System.Guid> AuthorId { get; set; }
        public Nullable<System.Guid> SignatoryId { get; set; }
        public Nullable<System.Guid> MatchingId { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.DateTime> DateSend { get; set; }
        public Nullable<System.DateTime> DateRead { get; set; }
        public string NumberLetter { get; set; }
        public string Subject { get; set; }
        public string Note { get; set; }
        public int StageId { get; set; }
        public int TypeId { get; set; }
        public int KindId { get; set; }
        public System.Guid StatusId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsReadOnly { get; set; }
        public int SubjectId { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual EXP_DIC_CorespondenceKind EXP_DIC_CorespondenceKind { get; set; }
        public virtual EXP_DIC_CorespondenceType EXP_DIC_CorespondenceType { get; set; }
        public virtual EXP_DIC_Stage EXP_DIC_Stage { get; set; }
        public virtual EXP_DrugDeclaration EXP_DrugDeclaration { get; set; }
        public virtual ICollection<EXP_DrugCorespondenceRemark> EXP_DrugCorespondenceRemark { get; set; }
        public virtual EXP_DIC_CorespondenceSubject EXP_DIC_CorespondenceSubject { get; set; }
    }
}
