//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_Activities
    {
        public EXP_Activities()
        {
            this.EXP_Tasks = new HashSet<EXP_Tasks>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TypeId { get; set; }
        public string TypeValue { get; set; }
        public string Text { get; set; }
        public System.Guid StatusId { get; set; }
        public string StatusValue { get; set; }
        public System.Guid AuthorId { get; set; }
        public string AuthorValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ExecutedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public System.Guid DocumentId { get; set; }
        public string DocumentValue { get; set; }
        public System.Guid DocumentTypeId { get; set; }
        public string DocumentTypeValue { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
    
        public virtual Dictionary ExpActivityStatus { get; set; }
        public virtual Dictionary ExpActivityType { get; set; }
        public virtual Dictionary ExpAgreedDocType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<EXP_Tasks> EXP_Tasks { get; set; }
    }
}
