//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_MaterialDirections
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string Number { get; set; }
        public System.Guid DrugDeclarationId { get; set; }
        public System.Guid StatusId { get; set; }
        public Nullable<System.Guid> SendEmployeeId { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.Guid> ExecutorEmployeeId { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public string Comment { get; set; }
    
        public virtual Dictionary Status { get; set; }
        public virtual Employee ExecutorEmp { get; set; }
        public virtual Employee SenderEmp { get; set; }
        public virtual EXP_DrugDeclaration EXP_DrugDeclaration { get; set; }
    }
}
