//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_ActivityTaskActualView
    {
        public System.Guid Id { get; set; }
        public System.Guid TypeId { get; set; }
        public string TypeValue { get; set; }
        public string Text { get; set; }
        public System.Guid StatusId { get; set; }
        public string StatusValue { get; set; }
        public System.Guid AuthorId { get; set; }
        public string AuthorValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ExecutedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public System.Guid DocumentId { get; set; }
        public string DocumentValue { get; set; }
        public System.Guid DocumentTypeId { get; set; }
        public string DocumentTypeValue { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public Nullable<System.Guid> TaskTypeId { get; set; }
        public string TaskTypeValue { get; set; }
        public Nullable<System.Guid> TaskStatusId { get; set; }
        public string TaskStatusValue { get; set; }
        public Nullable<int> TaskOrderNumber { get; set; }
        public string TaskNumber { get; set; }
        public string TaskText { get; set; }
        public Nullable<System.DateTime> TaskCreatedDate { get; set; }
        public Nullable<System.DateTime> TaskModifiedDate { get; set; }
        public Nullable<System.DateTime> TaskExecutedDate { get; set; }
        public Nullable<System.DateTime> TaskClosedDate { get; set; }
        public Nullable<System.Guid> TaskAuthorId { get; set; }
        public string TaskAuthorValue { get; set; }
        public Nullable<System.Guid> TaskExecutorId { get; set; }
        public string TaskExecutorValue { get; set; }
        public Nullable<System.Guid> TaskActivityId { get; set; }
        public Nullable<System.Guid> TaskParentTaskId { get; set; }
        public string TaskComment { get; set; }
    }
}
