//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugPrice
    {
        public long Id { get; set; }
        public string PrimaryValue { get; set; }
        public string SecondaryValue { get; set; }
        public string IntermediateValue { get; set; }
        public Nullable<double> CountUnit { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> ManufacturePrice { get; set; }
        public Nullable<double> RefPrice { get; set; }
        public Nullable<double> RegPrice { get; set; }
        public long DrugDosageId { get; set; }
    
        public virtual EXP_DrugDosage EXP_DrugDosage { get; set; }
    }
}
