//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugPatent
    {
        public long Id { get; set; }
        public System.Guid DrugDeclarationId { get; set; }
        public string PatentNumber { get; set; }
        public Nullable<System.DateTime> PatentDate { get; set; }
        public Nullable<System.DateTime> PatentExpiryDate { get; set; }
        public string NameOwner { get; set; }
        public string NameDocument { get; set; }
    
        public virtual EXP_DrugDeclaration EXP_DrugDeclaration { get; set; }
    }
}
