//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DIC_PrimaryOTD
    {
        public EXP_DIC_PrimaryOTD()
        {
            this.EXP_DIC_PrimaryOTD1 = new HashSet<EXP_DIC_PrimaryOTD>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
    
        public virtual ICollection<EXP_DIC_PrimaryOTD> EXP_DIC_PrimaryOTD1 { get; set; }
        public virtual EXP_DIC_PrimaryOTD EXP_DIC_PrimaryOTD2 { get; set; }
    }
}
