//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_ExpertisePharmaceuticalFinalDoc
    {
        public System.Guid Id { get; set; }
        public string Indicator1_1 { get; set; }
        public string Indicator2_1 { get; set; }
        public string Indicator2_2 { get; set; }
        public string Indicator2_3 { get; set; }
        public string Indicator2_4 { get; set; }
        public string Indicator3_1 { get; set; }
        public string Indicator3_2 { get; set; }
        public string Indicator3_3 { get; set; }
        public string Indicator4 { get; set; }
        public string Indicator5 { get; set; }
        public string Indicator6 { get; set; }
        public string Indicator7 { get; set; }
        public string Indicator12 { get; set; }
        public string Indicator13_1 { get; set; }
        public string Indicator13_2 { get; set; }
        public string Indicator13_3 { get; set; }
        public string Indicator14 { get; set; }
        public string Indicator15 { get; set; }
        public string Indicator16 { get; set; }
        public string Indicator17 { get; set; }
        public string Indicator18 { get; set; }
        public string Indicator19 { get; set; }
        public string Indicator20 { get; set; }
        public System.Guid DosageStageId { get; set; }
        public string ExpertConslusion { get; set; }
    
        public virtual EXP_ExpertiseStageDosage EXP_ExpertiseStageDosage { get; set; }
    }
}
