//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_CertificateOfCompletion
    {
        public System.Guid Id { get; set; }
        public Nullable<int> DicStageId { get; set; }
        public Nullable<System.Guid> DrugDeclarationId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.Guid> CreateEmployeeId { get; set; }
        public string Number { get; set; }
    
        public virtual Dictionary Status { get; set; }
        public virtual Employee CreateEmployee { get; set; }
        public virtual EXP_DIC_Stage EXP_DIC_Stage { get; set; }
        public virtual EXP_DrugDeclaration EXP_DrugDeclaration { get; set; }
    }
}
