//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugExportTrade
    {
        public long Id { get; set; }
        public System.Guid DrugDeclarationId { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public string NameEn { get; set; }
        public Nullable<long> CountryId { get; set; }
    
        public virtual EXP_DrugDeclaration EXP_DrugDeclaration { get; set; }
        public virtual sr_countries sr_countries { get; set; }
    }
}
