//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_ExpertiseStageDosageCommissionView
    {
        public int Id { get; set; }
        public string FullNumber { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsComplete { get; set; }
        public string CommisionType { get; set; }
        public string ConclusionName { get; set; }
        public string ConclusionComment { get; set; }
        public System.Guid StageId { get; set; }
        public long DrugDosageId { get; set; }
    }
}
