//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugDeclarationDirectionToPayView
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int TypeId { get; set; }
        public string TypeNameRu { get; set; }
        public string TypeNameKz { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public string NameEn { get; set; }
        public string DrugFormRu { get; set; }
        public string DrugFormKz { get; set; }
        public int StatusId { get; set; }
        public string StausName { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.Guid> DirectionToPayId { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<System.Guid> ExecuterId { get; set; }
    }
}
