//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugWrapping
    {
        public long Id { get; set; }
        public Nullable<int> WrappingTypeId { get; set; }
        public Nullable<int> WrappingKindId { get; set; }
        public Nullable<double> WrappingSize { get; set; }
        public Nullable<long> SizeMeasureId { get; set; }
        public Nullable<double> WrappingVolume { get; set; }
        public Nullable<long> VolumeMeasureId { get; set; }
        public Nullable<int> CountUnit { get; set; }
        public string Note { get; set; }
        public long DrugDosageId { get; set; }
        public string WrappingSizeStr { get; set; }
        public string WrappingVolumeStr { get; set; }
    
        public virtual EXP_DIC_WrappingType EXP_DIC_WrappingType { get; set; }
        public virtual sr_boxes sr_boxes { get; set; }
        public virtual sr_measures sr_measures { get; set; }
        public virtual sr_measures sr_measures1 { get; set; }
        public virtual EXP_DrugDosage EXP_DrugDosage { get; set; }
    }
}
