//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DIC_RemarkType
    {
        public EXP_DIC_RemarkType()
        {
            this.EXP_DrugAppDosageRemark = new HashSet<EXP_DrugAppDosageRemark>();
            this.EXP_DrugAppDosageResult = new HashSet<EXP_DrugAppDosageResult>();
            this.EXP_DrugPrimaryRemark = new HashSet<EXP_DrugPrimaryRemark>();
            this.EXP_DrugCorespondenceRemark = new HashSet<EXP_DrugCorespondenceRemark>();
            this.EXP_ExpertiseStageRemark = new HashSet<EXP_ExpertiseStageRemark>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
    
        public virtual ICollection<EXP_DrugAppDosageRemark> EXP_DrugAppDosageRemark { get; set; }
        public virtual ICollection<EXP_DrugAppDosageResult> EXP_DrugAppDosageResult { get; set; }
        public virtual ICollection<EXP_DrugPrimaryRemark> EXP_DrugPrimaryRemark { get; set; }
        public virtual ICollection<EXP_DrugCorespondenceRemark> EXP_DrugCorespondenceRemark { get; set; }
        public virtual ICollection<EXP_ExpertiseStageRemark> EXP_ExpertiseStageRemark { get; set; }
    }
}
