//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_TaskRegistryView
    {
        public System.Guid Id { get; set; }
        public System.Guid ActivityId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.Guid DocumentId { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public System.Guid StatusId { get; set; }
        public string StatusRu { get; set; }
        public string StatusKz { get; set; }
        public string StatusCode { get; set; }
        public System.Guid TypeId { get; set; }
        public string TaskTypeCode { get; set; }
        public System.Guid DocumentTypeId { get; set; }
        public string DocumentTypeRu { get; set; }
        public string DocumentTypeKz { get; set; }
        public string DocumentTypeCode { get; set; }
        public System.Guid AuthorId { get; set; }
        public string AuthorName { get; set; }
        public System.Guid ExecutorId { get; set; }
        public string ApproverNames { get; set; }
        public string SignerNames { get; set; }
        public string ActivityTypeCode { get; set; }
    }
}
