//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_ExpertiseStage
    {
        public EXP_ExpertiseStage()
        {
            this.ChildStages = new HashSet<EXP_ExpertiseStage>();
            this.EXP_ExpertiseStageDosage = new HashSet<EXP_ExpertiseStageDosage>();
            this.Executors = new HashSet<Employee>();
            this.EXP_ExpertiseStageRemark = new HashSet<EXP_ExpertiseStageRemark>();
            this.CommissionDrugDosageNeedCommissions = new HashSet<CommissionDrugDosageNeedCommission>();
            this.CommissionDrugDosages = new HashSet<CommissionDrugDosage>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid DeclarationId { get; set; }
        public int StageId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> FactEndDate { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<System.Guid> ParentStageId { get; set; }
        public bool IsHistory { get; set; }
        public string OtdIds { get; set; }
        public string OtdRemarks { get; set; }
        public bool IsSuspended { get; set; }
        public Nullable<System.DateTime> SuspendedStartDate { get; set; }
    
        public virtual EXP_DIC_Stage EXP_DIC_Stage { get; set; }
        public virtual EXP_DIC_StageResult EXP_DIC_StageResult { get; set; }
        public virtual EXP_DIC_StageStatus EXP_DIC_StageStatus { get; set; }
        public virtual EXP_DrugDeclaration EXP_DrugDeclaration { get; set; }
        public virtual ICollection<EXP_ExpertiseStage> ChildStages { get; set; }
        public virtual EXP_ExpertiseStage ParentStage { get; set; }
        public virtual ICollection<EXP_ExpertiseStageDosage> EXP_ExpertiseStageDosage { get; set; }
        public virtual ICollection<Employee> Executors { get; set; }
        public virtual ICollection<EXP_ExpertiseStageRemark> EXP_ExpertiseStageRemark { get; set; }
        public virtual ICollection<CommissionDrugDosageNeedCommission> CommissionDrugDosageNeedCommissions { get; set; }
        public virtual ICollection<CommissionDrugDosage> CommissionDrugDosages { get; set; }
    }
}
