//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DirectionToPays
    {
        public EXP_DirectionToPays()
        {
            this.EXP_DrugDeclaration = new HashSet<EXP_DrugDeclaration>();
            this.EXP_DirectionToPays_PriceList = new HashSet<EXP_DirectionToPays_PriceList>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public System.DateTime DirectionDate { get; set; }
        public Nullable<System.Guid> PayerId { get; set; }
        public string PayerValue { get; set; }
        public System.Guid CreateEmployeeId { get; set; }
        public string CreateEmployeeValue { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string InvoiceCode1C { get; set; }
        public string InvoiceNumber1C { get; set; }
        public Nullable<System.DateTime> InvoiceDatetime1C { get; set; }
        public Nullable<System.DateTime> PaymentDatetime1C { get; set; }
        public Nullable<decimal> PaymentValue1C { get; set; }
        public string PaymentComment1C { get; set; }
        public System.Guid StatusId { get; set; }
        public string StatusValue { get; set; }
        public int Type { get; set; }
        public string TypeValue { get; set; }
        public Nullable<int> PageCount { get; set; }
        public Nullable<decimal> PriceForPage { get; set; }
    
        public virtual ICollection<EXP_DrugDeclaration> EXP_DrugDeclaration { get; set; }
        public virtual Employee CreateEmployee { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Dictionary Status { get; set; }
        public virtual ICollection<EXP_DirectionToPays_PriceList> EXP_DirectionToPays_PriceList { get; set; }
    }
}
