//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DrugOrganizations
    {
        public long Id { get; set; }
        public System.Guid DrugDeclarationId { get; set; }
        public int Type { get; set; }
        public string NameKz { get; set; }
        public string NameRu { get; set; }
        public string NameEn { get; set; }
        public Nullable<System.Guid> CountryDicId { get; set; }
        public string AddressLegal { get; set; }
        public string AddressFact { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string BossFio { get; set; }
        public string BossPosition { get; set; }
        public string ContactFio { get; set; }
        public string ContactPosition { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<System.Guid> OrgManufactureTypeDicId { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocExpiryDate { get; set; }
        public Nullable<System.Guid> ObjectId { get; set; }
        public Nullable<System.Guid> OpfTypeDicId { get; set; }
        public string BankName { get; set; }
        public string BankIik { get; set; }
        public Nullable<System.Guid> BankCurencyDicId { get; set; }
        public string BankSwift { get; set; }
        public string Bin { get; set; }
        public bool IsResident { get; set; }
        public Nullable<System.Guid> PayerTypeDicId { get; set; }
        public string BossLastName { get; set; }
        public string BossFirstName { get; set; }
        public string BossMiddleName { get; set; }
        public string PaymentBill { get; set; }
        public string Iin { get; set; }
        public string BankBik { get; set; }
    
        public virtual EXP_DrugDeclaration EXP_DrugDeclaration { get; set; }
    }
}
