//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DirectionToPaysView
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public System.DateTime DirectionDate { get; set; }
        public string ApplicationNumbers { get; set; }
        public string ApplicationDates { get; set; }
        public string RegistrationForm { get; set; }
        public string TradeNameKz { get; set; }
        public string TradeNameRu { get; set; }
        public string TradeNameEn { get; set; }
        public string DrugFormKz { get; set; }
        public string DrugFormRu { get; set; }
        public string DrugFormEn { get; set; }
        public string ManufactureKz { get; set; }
        public string ManufactureRu { get; set; }
        public string ManufactureEn { get; set; }
        public string ExpertDisplayName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Currency { get; set; }
        public string PriceListNameKz { get; set; }
        public string PriceListNameRu { get; set; }
        public string PriceListNameEn { get; set; }
        public string PriceListValue { get; set; }
        public string InvoiceNumber1C { get; set; }
        public Nullable<System.DateTime> InvoiceDatetime1C { get; set; }
        public Nullable<System.DateTime> PaymentDatetime1C { get; set; }
        public Nullable<decimal> PaymentValue1C { get; set; }
        public string PaymentComment1C { get; set; }
        public System.Guid StatusId { get; set; }
        public string StatusCode { get; set; }
        public string StatusName { get; set; }
        public string StatusNameKz { get; set; }
        public System.Guid CreateEmployeeId { get; set; }
        public Nullable<System.Guid> ExecutorId { get; set; }
        public string ExecutorName { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> PageCount { get; set; }
        public int Type { get; set; }
    }
}
