//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_DrugDosageStagePrevCommissionView
    {
        public long DrugDosageId { get; set; }
        public System.Guid StageId { get; set; }
        public int CommissionId { get; set; }
        public int DrevComId { get; set; }
        public string DrevComFullNumber { get; set; }
        public System.DateTime PrevComDate { get; set; }
    }
}
