//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_DirectionToPays_PriceList
    {
        public System.Guid DirectionToPayId { get; set; }
        public System.Guid PriceListId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual EXP_DirectionToPays EXP_DirectionToPays { get; set; }
        public virtual EXP_PriceList EXP_PriceList { get; set; }
    }
}
