//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public System.Guid Id { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeValue { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Organization { get; set; }
        public string Country { get; set; }
        public string Position { get; set; }
        public string Note { get; set; }
    }
}
