//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLinkView
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string Category { get; set; }
        public string ParentFileName { get; set; }
    }
}
