//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLink
    {
        public FileLink()
        {
            this.FileLinks1 = new HashSet<FileLink>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> OwnerId { get; set; }
        public bool IsDeleted { get; set; }
        public string Comment { get; set; }
        public string Language { get; set; }
        public Nullable<int> PageNumbers { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool IsSigned { get; set; }
    
        public virtual Dictionary FileCategory { get; set; }
        public virtual ICollection<FileLink> FileLinks1 { get; set; }
        public virtual FileLink ParentFile { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual EXP_DIC_Stage EXP_DIC_Stage { get; set; }
        public virtual DIC_FileLinkStatus DIC_FileLinkStatus { get; set; }
    }
}
