//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLinksCategoryCom
    {
        public FileLinksCategoryCom()
        {
            this.FileLinksCategoryComRecords = new HashSet<FileLinksCategoryComRecord>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public bool IsError { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<FileLinksCategoryComRecord> FileLinksCategoryComRecords { get; set; }
    }
}
