//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public System.Guid GroupId { get; set; }
        public string OperationId { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public System.Guid ObjectId { get; set; }
        public string Record { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string UserName { get; set; }
        public string Ip { get; set; }
    }
}
