//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class I1c_trl_Application
    {
        public System.Guid Id { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string ApplicationNumber { get; set; }
        public Nullable<System.DateTime> ApplicationDatetime { get; set; }
        public string TranslatorFIO { get; set; }
        public Nullable<System.Guid> TranslatorId { get; set; }
        public Nullable<int> PageQuantity { get; set; }
        public Nullable<decimal> PagePrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string InvoiceCode_1C { get; set; }
        public string InvoiceNumber_1C { get; set; }
        public Nullable<System.DateTime> InvoiceDatetime_1C { get; set; }
        public System.DateTime ExportDatetime { get; set; }
        public Nullable<System.DateTime> ImportDatetime { get; set; }
        public System.Guid refPrimaryApplication { get; set; }
    }
}
