//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class I1c_lims_ContractProducts
    {
        public System.Guid Id { get; set; }
        public string ProductId { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> QuantityVolume { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> ExportDatetime { get; set; }
        public Nullable<System.DateTime> ImportDatetime { get; set; }
    }
}
