//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class I1c_primary_Applications
    {
        public System.Guid Id { get; set; }
        public System.DateTime ExportDatetime { get; set; }
        public Nullable<System.DateTime> ImportDatetime { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public string ApplicationNumber { get; set; }
        public Nullable<System.DateTime> ApplicationDatetime { get; set; }
        public string ApplicationType { get; set; }
        public string Producer { get; set; }
        public Nullable<System.Guid> ProducerId { get; set; }
        public string Applicant { get; set; }
        public Nullable<System.Guid> ApplicantId { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public string DoverennostNumber { get; set; }
        public Nullable<System.DateTime> DoverennostCreatedDate { get; set; }
        public Nullable<System.DateTime> DoverennostExpiryDate { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Payer { get; set; }
        public Nullable<System.Guid> PayerId { get; set; }
        public string PayerAddress { get; set; }
        public string PayerBank { get; set; }
        public string PayerAccount { get; set; }
        public string PayerBIK { get; set; }
        public string PayerSWIFT { get; set; }
        public string PayerBIN { get; set; }
        public string PayerIIN { get; set; }
        public string PayerCurrency { get; set; }
        public string PayerCurrencyCode { get; set; }
        public Nullable<System.Guid> PayerCurrencyId { get; set; }
        public string Country { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public Nullable<bool> IsResident { get; set; }
        public Nullable<bool> IsLegal { get; set; }
        public string InvoiceNumber1C { get; set; }
        public Nullable<System.DateTime> InvoiceDatetime1C { get; set; }
        public string StatementNumber { get; set; }
        public string DrugTradeName { get; set; }
        public string DrugTradeNameKz { get; set; }
        public string DrugPackage { get; set; }
        public string DrugPackageKz { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    }
}
