//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class I1c_primary_ApplicationElements
    {
        public System.Guid Id { get; set; }
        public Nullable<decimal> Dosage { get; set; }
        public string MeasureName { get; set; }
        public string RegNumber { get; set; }
        public string ConcentrationRu { get; set; }
        public string ConcentrationKz { get; set; }
        public System.Guid refApplication { get; set; }
    }
}
