//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class I1c_primary_ObkPriceListElements
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PriceListId { get; set; }
        public string PriceListName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string DrugTradeName { get; set; }
        public string DrugTradeNameKz { get; set; }
        public string DrugFormName { get; set; }
        public string DrugFormNameKz { get; set; }
        public Nullable<System.Guid> refContractId { get; set; }
    }
}
