//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installation
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string ManufacturerFactory { get; set; }
        public string Country { get; set; }
        public string FactoryNumber { get; set; }
        public string InvertoryNumber { get; set; }
        public string LaboratoryRoom { get; set; }
        public string InstallationYear { get; set; }
        public string Note { get; set; }
        public string CheckDate { get; set; }
        public string Type { get; set; }
        public string Laboratory { get; set; }
        public string TypeIn { get; set; }
        public string BuhList { get; set; }
        public string State { get; set; }
        public string StateIn { get; set; }
    }
}
