//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lims_ActivityView
    {
        public string DisplayName { get; set; }
        public Nullable<int> AppPoaNewCount { get; set; }
        public Nullable<int> AppPoaSendedTo1CCount { get; set; }
        public Nullable<int> AppPoaReceivedFrom1CCount { get; set; }
        public Nullable<int> TmcReceivedFrom1CCount { get; set; }
        public Nullable<int> AppRecCount { get; set; }
        public Nullable<int> AppRecIssuedCount { get; set; }
        public Nullable<int> AppRecUsedCount { get; set; }
        public int ReportByEmployee { get; set; }
        public Nullable<int> ReportByDepartment { get; set; }
        public Nullable<int> ReportByIc { get; set; }
    }
}
