//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkDictionary
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DictionaryId { get; set; }
        public Nullable<System.Guid> OwnerId { get; set; }
        public string PropertyName { get; set; }
    }
}
