//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_ContractSignedDatas
    {
        public System.Guid ContractId { get; set; }
        public string ApplicantSign { get; set; }
        public Nullable<System.DateTime> ApplicantSignDate { get; set; }
        public string CeoSign { get; set; }
        public Nullable<System.DateTime> CeoSignDate { get; set; }
    
        public virtual OBK_Contract OBK_Contract { get; set; }
    }
}
