//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_Ref_PriceList
    {
        public OBK_Ref_PriceList()
        {
            this.OBK_ContractPrice = new HashSet<OBK_ContractPrice>();
        }
    
        public System.Guid Id { get; set; }
        public int TypeId { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.Guid UnitId { get; set; }
        public double Price { get; set; }
        public System.Guid ServiceTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DegreeRiskId { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        public virtual ICollection<OBK_ContractPrice> OBK_ContractPrice { get; set; }
        public virtual OBK_Ref_DegreeRisk OBK_Ref_DegreeRisk { get; set; }
        public virtual OBK_Ref_ServiceType OBK_Ref_ServiceType { get; set; }
        public virtual OBK_Ref_Type OBK_Ref_Type { get; set; }
    }
}
