//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_Ref_CertificateType
    {
        public OBK_Ref_CertificateType()
        {
            this.OBK_AssessmentDeclaration = new HashSet<OBK_AssessmentDeclaration>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<OBK_AssessmentDeclaration> OBK_AssessmentDeclaration { get; set; }
    }
}
