//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_ContractExtHistory
    {
        public System.Guid Id { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid StatusId { get; set; }
        public System.Guid ContractId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual OBK_Contract OBK_Contract { get; set; }
        public virtual OBK_Ref_ContractExtHistoryStatus OBK_Ref_ContractExtHistoryStatus { get; set; }
    }
}
