//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_AssessmentDeclarationRegisterView
    {
        public int StatusId { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> FirstSendDate { get; set; }
        public string DeclarantName { get; set; }
        public int StageStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.Guid ExecutorId { get; set; }
        public string RegType { get; set; }
        public System.Guid StageId { get; set; }
        public string StatusName { get; set; }
        public string StageStatusCode { get; set; }
        public string StageCode { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string CountryNameRu { get; set; }
        public string ContractNumber { get; set; }
    }
}
