//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_AssessmentDeclaration
    {
        public OBK_AssessmentDeclaration()
        {
            this.OBK_AssessmentDeclarationHistory = new HashSet<OBK_AssessmentDeclarationHistory>();
            this.OBK_AssessmentStage = new HashSet<OBK_AssessmentStage>();
            this.OBK_AssessmentDeclarationCom = new HashSet<OBK_AssessmentDeclarationCom>();
            this.OBK_AssessmentDeclarationFieldHistory = new HashSet<OBK_AssessmentDeclarationFieldHistory>();
            this.OBK_StageExpDocumentResult = new HashSet<OBK_StageExpDocumentResult>();
            this.OBK_CertificateOfCompletion = new HashSet<OBK_CertificateOfCompletion>();
        }
    
        public System.Guid Id { get; set; }
        public string CertificateGMP { get; set; }
        public string CertificateNumber { get; set; }
        public bool AssuranceCheck { get; set; }
        public bool OrderCheck { get; set; }
        public bool StabilityCheck { get; set; }
        public bool PaymentCheck { get; set; }
        public int Type_Id { get; set; }
        public Nullable<System.Guid> Contract_Id { get; set; }
        public Nullable<System.DateTime> CertificateDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> CertificateGMPCheck { get; set; }
        public int StatusId { get; set; }
        public string InvoiceRu { get; set; }
        public string InvoiceKz { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceContractRu { get; set; }
        public string InvoiceContractKz { get; set; }
        public string InvoiceAgentLastName { get; set; }
        public string InvoiceAgentFirstName { get; set; }
        public string InvoiceAgentMiddelName { get; set; }
        public string InvoiceAgentPositionName { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.Guid> ExecuterId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DesignDate { get; set; }
        public System.Guid EmployeeId { get; set; }
        public Nullable<System.DateTime> FirstSendDate { get; set; }
        public bool IsSigned { get; set; }
        public string DesignNote { get; set; }
        public Nullable<System.Guid> CertificateCountryId { get; set; }
        public string CertificateOrganization { get; set; }
        public Nullable<System.DateTime> CertificateStartDate { get; set; }
        public Nullable<int> CertificateTypeId { get; set; }
        public Nullable<System.DateTime> InvoiceContractDate { get; set; }
        public string CertificateManufacturName { get; set; }
    
        public virtual OBK_Ref_Type OBK_Ref_Type { get; set; }
        public virtual OBK_Ref_Status OBK_Ref_Status { get; set; }
        public virtual ICollection<OBK_AssessmentDeclarationHistory> OBK_AssessmentDeclarationHistory { get; set; }
        public virtual ICollection<OBK_AssessmentStage> OBK_AssessmentStage { get; set; }
        public virtual ICollection<OBK_AssessmentDeclarationCom> OBK_AssessmentDeclarationCom { get; set; }
        public virtual ICollection<OBK_AssessmentDeclarationFieldHistory> OBK_AssessmentDeclarationFieldHistory { get; set; }
        public virtual Dictionary Dictionary { get; set; }
        public virtual OBK_Ref_CertificateType OBK_Ref_CertificateType { get; set; }
        public virtual ICollection<OBK_StageExpDocumentResult> OBK_StageExpDocumentResult { get; set; }
        public virtual ICollection<OBK_CertificateOfCompletion> OBK_CertificateOfCompletion { get; set; }
    }
}
