//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_ContractCom
    {
        public OBK_ContractCom()
        {
            this.OBK_ContractComRecord = new HashSet<OBK_ContractComRecord>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public bool IsError { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsDelete { get; set; }
        public string ControlId { get; set; }
    
        public virtual OBK_Contract OBK_Contract { get; set; }
        public virtual ICollection<OBK_ContractComRecord> OBK_ContractComRecord { get; set; }
    }
}
