//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class obk_certification_copies
    {
        public long id { get; set; }
        public long copies_application_id { get; set; }
        public long certification_id { get; set; }
        public string blank_begin_number { get; set; }
        public string blank_end_number { get; set; }
        public string certificate_reg_number { get; set; }
        public string certificate_blank_number { get; set; }
        public string comment { get; set; }
    
        public virtual obk_certifications obk_certifications { get; set; }
    }
}
