//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_Procunts_Series
    {
        public OBK_Procunts_Series()
        {
            this.OBK_StageExpDocument = new HashSet<OBK_StageExpDocument>();
            this.OBK_Products_SeriesCom = new HashSet<OBK_Products_SeriesCom>();
        }
    
        public int Id { get; set; }
        public string Series { get; set; }
        public string SeriesStartdate { get; set; }
        public string SeriesEndDate { get; set; }
        public string SeriesParty { get; set; }
        public int OBK_RS_ProductsId { get; set; }
        public Nullable<long> SeriesMeasureId { get; set; }
    
        public virtual OBK_RS_Products OBK_RS_Products { get; set; }
        public virtual sr_measures sr_measures { get; set; }
        public virtual ICollection<OBK_StageExpDocument> OBK_StageExpDocument { get; set; }
        public virtual ICollection<OBK_Products_SeriesCom> OBK_Products_SeriesCom { get; set; }
    }
}
