//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_Contract
    {
        public OBK_Contract()
        {
            this.OBK_RS_Products = new HashSet<OBK_RS_Products>();
            this.OBK_ContractPrice = new HashSet<OBK_ContractPrice>();
            this.OBK_ContractCom = new HashSet<OBK_ContractCom>();
            this.OBK_ContractExtHistory = new HashSet<OBK_ContractExtHistory>();
            this.OBK_ContractStage = new HashSet<OBK_ContractStage>();
            this.OBK_DirectionToPayments = new HashSet<OBK_DirectionToPayments>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> DeclarantId { get; set; }
        public Nullable<System.Guid> DeclarantContactId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> ContractType { get; set; }
        public Nullable<System.Guid> ExpertOrganization { get; set; }
        public Nullable<System.Guid> Signer { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
    
        public virtual OBK_Declarant OBK_Declarant { get; set; }
        public virtual OBK_DeclarantContact OBK_DeclarantContact { get; set; }
        public virtual OBK_Ref_Status OBK_Ref_Status { get; set; }
        public virtual OBK_Ref_Type OBK_Ref_Type { get; set; }
        public virtual ICollection<OBK_RS_Products> OBK_RS_Products { get; set; }
        public virtual ICollection<OBK_ContractPrice> OBK_ContractPrice { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<OBK_ContractCom> OBK_ContractCom { get; set; }
        public virtual ICollection<OBK_ContractExtHistory> OBK_ContractExtHistory { get; set; }
        public virtual OBK_ContractSignedDatas OBK_ContractSignedDatas { get; set; }
        public virtual ICollection<OBK_ContractStage> OBK_ContractStage { get; set; }
        public virtual ICollection<OBK_DirectionToPayments> OBK_DirectionToPayments { get; set; }
    }
}
