//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_ContractStage
    {
        public OBK_ContractStage()
        {
            this.OBK_ContractStage1 = new HashSet<OBK_ContractStage>();
            this.OBK_ContractStageExecutors = new HashSet<OBK_ContractStageExecutors>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public int StageId { get; set; }
        public int StageStatusId { get; set; }
        public Nullable<System.Guid> ParentStageId { get; set; }
        public Nullable<int> ResultId { get; set; }
    
        public virtual OBK_Contract OBK_Contract { get; set; }
        public virtual ICollection<OBK_ContractStage> OBK_ContractStage1 { get; set; }
        public virtual OBK_ContractStage OBK_ContractStage2 { get; set; }
        public virtual OBK_Ref_Stage OBK_Ref_Stage { get; set; }
        public virtual OBK_Ref_StageStatus OBK_Ref_StageStatus { get; set; }
        public virtual ICollection<OBK_ContractStageExecutors> OBK_ContractStageExecutors { get; set; }
    }
}
