//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_ContractPrice
    {
        public OBK_ContractPrice()
        {
            this.OBK_ContractPriceCom = new HashSet<OBK_ContractPriceCom>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PriceRefId { get; set; }
        public int Count { get; set; }
        public double PriceWithoutTax { get; set; }
        public double PriceWithTax { get; set; }
        public Nullable<int> ProductId { get; set; }
        public System.Guid ContractId { get; set; }
    
        public virtual OBK_Contract OBK_Contract { get; set; }
        public virtual OBK_Ref_PriceList OBK_Ref_PriceList { get; set; }
        public virtual OBK_RS_Products OBK_RS_Products { get; set; }
        public virtual ICollection<OBK_ContractPriceCom> OBK_ContractPriceCom { get; set; }
    }
}
