//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_Ref_ServiceType
    {
        public OBK_Ref_ServiceType()
        {
            this.OBK_Ref_PriceList = new HashSet<OBK_Ref_PriceList>();
        }
    
        public System.Guid Id { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
    
        public virtual ICollection<OBK_Ref_PriceList> OBK_Ref_PriceList { get; set; }
    }
}
