//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_MtPart
    {
        public System.Guid Id { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> PartNumber { get; set; }
        public string Model { get; set; }
        public string Specification { get; set; }
        public string SpecificationKz { get; set; }
        public string ProducerName { get; set; }
        public string CountryName { get; set; }
        public string ProducerNameKz { get; set; }
        public string CountryNameKz { get; set; }
        public string Name { get; set; }
        public string NameKz { get; set; }
    
        public virtual OBK_RS_Products OBK_RS_Products { get; set; }
    }
}
