//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class obk_appendix
    {
        public obk_appendix()
        {
            this.obk_appendix_series = new HashSet<obk_appendix_series>();
        }
    
        public long id { get; set; }
        public long certification_id { get; set; }
        public string appendix_number { get; set; }
        public string comment { get; set; }
    
        public virtual obk_certifications obk_certifications { get; set; }
        public virtual ICollection<obk_appendix_series> obk_appendix_series { get; set; }
    }
}
