//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_AssessmentDeclarationView
    {
        public System.Guid Id { get; set; }
        public System.Guid OwnerId { get; set; }
        public int Type_Id { get; set; }
        public int StatusId { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string StausName { get; set; }
        public string TypeName { get; set; }
        public System.DateTime SortDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
