//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_Declarant
    {
        public OBK_Declarant()
        {
            this.OBK_Contract = new HashSet<OBK_Contract>();
            this.OBK_DeclarantContact = new HashSet<OBK_DeclarantContact>();
            this.OBK_DirectionToPayments = new HashSet<OBK_DirectionToPayments>();
        }
    
        public System.Guid Id { get; set; }
        public string NameKz { get; set; }
        public string NameRu { get; set; }
        public string NameEn { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string Iin { get; set; }
        public string Bin { get; set; }
        public Nullable<System.Guid> OrganizationFormId { get; set; }
        public bool IsConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsResident { get; set; }
    
        public virtual ICollection<OBK_Contract> OBK_Contract { get; set; }
        public virtual ICollection<OBK_DeclarantContact> OBK_DeclarantContact { get; set; }
        public virtual ICollection<OBK_DirectionToPayments> OBK_DirectionToPayments { get; set; }
    }
}
