//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class obk_appendix_series
    {
        public long id { get; set; }
        public long appendix_id { get; set; }
        public long product_id { get; set; }
    
        public virtual obk_appendix obk_appendix { get; set; }
        public virtual obk_products obk_products { get; set; }
    }
}
