//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_StageExpDocument
    {
        public System.Guid Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductSeriesId { get; set; }
        public bool ExpResult { get; set; }
        public Nullable<System.DateTime> ExpStartDate { get; set; }
        public Nullable<System.DateTime> ExpEndDate { get; set; }
        public string ExpReasonNameRu { get; set; }
        public string ExpReasonNameKz { get; set; }
        public string ExpProductNameRu { get; set; }
        public string ExpProductNameKz { get; set; }
        public string ExpNomenclatureRu { get; set; }
        public string ExpNomenclatureKz { get; set; }
        public string ExpAddInfoRu { get; set; }
        public string ExpAddInfoKz { get; set; }
        public string ExpConclusionNumber { get; set; }
        public string ExpBlankNumber { get; set; }
        public bool ExpApplication { get; set; }
        public string ExpApplicationNumber { get; set; }
        public string ExpExecutorSign { get; set; }
        public Nullable<System.Guid> ExecutorId { get; set; }
    
        public virtual OBK_Procunts_Series OBK_Procunts_Series { get; set; }
        public virtual OBK_RS_Products OBK_RS_Products { get; set; }
    }
}
