//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_ContractStageExecutors
    {
        public System.Guid ContractStageId { get; set; }
        public System.Guid ExecutorId { get; set; }
        public int ExecutorType { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual OBK_ContractStage OBK_ContractStage { get; set; }
    }
}
