//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_ContractRegisterView
    {
        public System.Guid ContractId { get; set; }
        public string ContractTypeRu { get; set; }
        public string ContractTypeKz { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime ContractCreatedDate { get; set; }
        public Nullable<System.DateTime> ContractSendDate { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.Guid> ContractSigner { get; set; }
        public string DeclarantNameRu { get; set; }
        public System.Guid ExecutorId { get; set; }
        public int ExecutorType { get; set; }
        public int ContractStatusId { get; set; }
        public string ContractStatusNameRu { get; set; }
        public int StageStatusId { get; set; }
        public string StageStatusNameRu { get; set; }
        public string StageStatusCode { get; set; }
        public System.Guid ContractStageId { get; set; }
        public int ContractStageStageId { get; set; }
        public Nullable<int> StageCOZResult { get; set; }
        public Nullable<int> StageUOBKResult { get; set; }
        public string StageUOBKExecutor { get; set; }
        public Nullable<int> StageDEFResult { get; set; }
        public string StageDEFExecutor { get; set; }
    }
}
