//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class obk_currencies
    {
        public obk_currencies()
        {
            this.obk_exchangerate = new HashSet<obk_exchangerate>();
        }
    
        public int id { get; set; }
        public string currency_name { get; set; }
        public string short_name { get; set; }
        public string currency_code { get; set; }
        public string abbreviation { get; set; }
    
        public virtual ICollection<obk_exchangerate> obk_exchangerate { get; set; }
    }
}
