//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_DirectionToPayments
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public System.DateTime DirectionDate { get; set; }
        public System.Guid ContractId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.Guid> PayerId { get; set; }
        public string PayerValue { get; set; }
        public System.Guid CreateEmployeeId { get; set; }
        public string CreateEmployeeValue { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid StatusId { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceNumber1C { get; set; }
        public Nullable<System.DateTime> InvoiceDatetime1C { get; set; }
        public bool IsPaid { get; set; }
        public bool IsNotFullPaid { get; set; }
        public Nullable<System.DateTime> PaymentDatetime { get; set; }
        public Nullable<decimal> PaymentValue { get; set; }
        public Nullable<decimal> PaymentBill { get; set; }
        public string SendNotification { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual OBK_Contract OBK_Contract { get; set; }
        public virtual OBK_Declarant OBK_Declarant { get; set; }
        public virtual OBK_DirectionSignData OBK_DirectionSignData { get; set; }
    }
}
