//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_Ref_Type
    {
        public OBK_Ref_Type()
        {
            this.OBK_Contract = new HashSet<OBK_Contract>();
            this.OBK_Ref_PriceList = new HashSet<OBK_Ref_PriceList>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int ViewOption { get; set; }
    
        public virtual ICollection<OBK_Contract> OBK_Contract { get; set; }
        public virtual ICollection<OBK_Ref_PriceList> OBK_Ref_PriceList { get; set; }
    }
}
