//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_DirectionToPaymentsView
    {
        public System.DateTime CreateDate { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid CreateEmployeeId { get; set; }
        public string CreateEmployeeValue { get; set; }
        public Nullable<System.Guid> PayerId { get; set; }
        public string PayerValue { get; set; }
        public System.Guid StatusId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DisplayName { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string StatusCode { get; set; }
        public string InvoiceNumber { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public System.Guid Id { get; set; }
        public string InvoiceNumber1C { get; set; }
        public Nullable<System.Guid> ExecutorId { get; set; }
        public string ExecutorSign { get; set; }
        public Nullable<System.Guid> ChiefAccountantId { get; set; }
        public string ChiefAccountantSign { get; set; }
        public Nullable<System.Guid> ExpertOrganization { get; set; }
        public string ChiefName { get; set; }
        public string ExecutorName { get; set; }
    }
}
