//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class obk_product_cost
    {
        public long id { get; set; }
        public decimal cost { get; set; }
        public int currency_id { get; set; }
        public Nullable<System.DateTime> date_cost { get; set; }
    
        public virtual obk_products obk_products { get; set; }
    }
}
