//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_DirectionSignData
    {
        public System.Guid DirectionToPaymentId { get; set; }
        public Nullable<System.Guid> ExecutorId { get; set; }
        public string ExecutorSign { get; set; }
        public Nullable<System.DateTime> ExecutorSignDate { get; set; }
        public Nullable<System.Guid> ChiefAccountantId { get; set; }
        public string ChiefAccountantSign { get; set; }
        public Nullable<System.DateTime> ChiefAccountantSignDate { get; set; }
    
        public virtual OBK_DirectionToPayments OBK_DirectionToPayments { get; set; }
    }
}
