//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_Ref_Status
    {
        public OBK_Ref_Status()
        {
            this.OBK_Contract = new HashSet<OBK_Contract>();
            this.OBK_AssessmentDeclarationHistory = new HashSet<OBK_AssessmentDeclarationHistory>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
    
        public virtual ICollection<OBK_Contract> OBK_Contract { get; set; }
        public virtual ICollection<OBK_AssessmentDeclarationHistory> OBK_AssessmentDeclarationHistory { get; set; }
    }
}
