//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBK_ContractPriceCom
    {
        public OBK_ContractPriceCom()
        {
            this.OBK_ContractPriceComRecord = new HashSet<OBK_ContractPriceComRecord>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractPriceId { get; set; }
        public bool IsError { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual OBK_ContractPrice OBK_ContractPrice { get; set; }
        public virtual ICollection<OBK_ContractPriceComRecord> OBK_ContractPriceComRecord { get; set; }
    }
}
