//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrphanDrugsIcdDeseasesView
    {
        public System.Guid Id { get; set; }
        public Nullable<long> LinkDicId { get; set; }
        public long OrphanDrugsId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<long> IcdDeseasesId { get; set; }
        public string CodeICD { get; set; }
        public string DiseaseOfICD { get; set; }
        public string SysnonimAndRareDesease { get; set; }
    }
}
