//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PackageTypeDicId { get; set; }
        public Nullable<System.Guid> PackageNameDicId { get; set; }
        public string PackageName { get; set; }
        public decimal Size { get; set; }
        public Nullable<System.Guid> SizeMeasureTypeDicId { get; set; }
        public decimal Volume { get; set; }
        public Nullable<System.Guid> VolumeMeasureTypeDicId { get; set; }
        public int Count { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> ObjectId { get; set; }
    }
}
