//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionKey
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public int Type { get; set; }
        public string KeyName { get; set; }
        public string KeyDescription { get; set; }
        public string GroupName { get; set; }
    }
}
