//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_ProtocolProductPrices
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ProtocolId { get; set; }
        public string ProductNameRu { get; set; }
        public string ProductNameKz { get; set; }
        public decimal PriceFirst { get; set; }
        public decimal PriceNew { get; set; }
        public Nullable<System.Guid> PriceProjectId { get; set; }
    
        public virtual PP_Protocols PP_Protocols { get; set; }
    }
}
