//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_Protocols
    {
        public PP_Protocols()
        {
            this.PP_ProtocolComissionMembers = new HashSet<PP_ProtocolComissionMembers>();
            this.PP_ProtocolProductPrices = new HashSet<PP_ProtocolProductPrices>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public string Number { get; set; }
        public System.DateTime ProtocolDate { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.Guid> ChiefId { get; set; }
        public Nullable<System.Guid> RequesterId { get; set; }
        public string RequesterName { get; set; }
        public string AdditionalPersonName { get; set; }
        public bool IsImn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<PP_ProtocolComissionMembers> PP_ProtocolComissionMembers { get; set; }
        public virtual ICollection<PP_ProtocolProductPrices> PP_ProtocolProductPrices { get; set; }
    }
}
