//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_ProcessingJournal
    {
        public System.Guid Id { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public Nullable<int> SelectStatus { get; set; }
        public string Number { get; set; }
        public string IncomeNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid ProxyOrganizationId { get; set; }
        public string ProxyOrgName { get; set; }
        public System.Guid ManufacturerOrganizationId { get; set; }
        public string ManufacturerOrgName { get; set; }
        public string RegNumber { get; set; }
        public string MnnRu { get; set; }
        public string MnnEn { get; set; }
        public string TradeName { get; set; }
        public Nullable<bool> HasSign { get; set; }
        public Nullable<System.DateTime> EndExecDate { get; set; }
    }
}
