//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public System.Guid Id { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public System.Guid PriceProjectId { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public decimal ManufacturerPrice { get; set; }
        public Nullable<System.Guid> ManufacturerPriceCurrencyDicId { get; set; }
        public string ManufacturerPriceNote { get; set; }
        public decimal LimitPrice { get; set; }
        public Nullable<System.Guid> LimitPriceCurrencyDicId { get; set; }
        public string LimitPriceNote { get; set; }
        public decimal AvgOptPrice { get; set; }
        public Nullable<System.Guid> AvgOptPriceCurrencyDicId { get; set; }
        public string AvgOptPriceNote { get; set; }
        public decimal AvgRozPrice { get; set; }
        public Nullable<System.Guid> AvgRozPriceCurrencyDicId { get; set; }
        public string AvgRozPriceNote { get; set; }
        public decimal CipPrice { get; set; }
        public Nullable<System.Guid> CipPriceCurrencyDicId { get; set; }
        public Nullable<System.Guid> RefPriceTypeDicId { get; set; }
        public decimal RefPrice { get; set; }
        public Nullable<System.Guid> RefPriceCurrencyDicId { get; set; }
        public decimal OwnerPrice { get; set; }
        public Nullable<System.Guid> OwnerPriceCurrencyDicId { get; set; }
        public decimal BritishPrice { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<System.Guid> UnitPriceCurrencyDicId { get; set; }
        public decimal BritishCost { get; set; }
        public decimal AvgObkCost { get; set; }
        public decimal AvgRznCost { get; set; }
        public decimal AvgOptCost { get; set; }
        public decimal ZakupCost { get; set; }
        public decimal LimitCost { get; set; }
        public decimal MinimalCost { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> MtPartsId { get; set; }
        public decimal OriginalCost { get; set; }
        public decimal MarkupCost { get; set; }
        public decimal MarkupCostOpt { get; set; }
        public Nullable<System.DateTime> CalcDateStart { get; set; }
        public Nullable<System.DateTime> CalcDateEnd { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Description { get; set; }
        public bool IsIncluded { get; set; }
        public bool IsUnitPrice { get; set; }
        public bool IsManufacturerPrice { get; set; }
        public bool IsLimitPrice { get; set; }
        public bool IsAvgOptPrice { get; set; }
        public bool IsAvgRozPrice { get; set; }
    }
}
