//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceProjectArchiveView
    {
        public System.Guid Id { get; set; }
        public string MnnCode { get; set; }
        public string MnnRu { get; set; }
        public string DrugDescription { get; set; }
        public string DrugName { get; set; }
        public string CountPackage { get; set; }
        public string ProducerName { get; set; }
        public string ProducerCountry { get; set; }
        public string RegNumber { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> RegEndDate { get; set; }
        public string ProxyName { get; set; }
        public string RequesterContacts { get; set; }
        public Nullable<System.Guid> LsTypeDicId { get; set; }
        public string LsTypeName { get; set; }
        public Nullable<decimal> MarginalPriceTn622 { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<System.DateTime> BasePriceDate { get; set; }
        public Nullable<decimal> TalkPrice { get; set; }
        public Nullable<System.DateTime> TalkPriceDate { get; set; }
        public Nullable<decimal> BritishPrice { get; set; }
        public Nullable<decimal> MinRefPrice2016 { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<decimal> FinalFixPrice { get; set; }
        public Nullable<decimal> FinalMarginalPriceTn { get; set; }
        public Nullable<decimal> LimitCost { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> RequestOrderType { get; set; }
        public Nullable<int> RequestOrderYear { get; set; }
    }
}
