//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceProjectCom
    {
        public PriceProjectCom()
        {
            this.PriceProjectComRecords = new HashSet<PriceProjectComRecord>();
        }
    
        public long Id { get; set; }
        public System.Guid PriceProjectId { get; set; }
        public bool IsError { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsDelete { get; set; }
        public string ControlId { get; set; }
    
        public virtual PriceProject PriceProject { get; set; }
        public virtual ICollection<PriceProjectComRecord> PriceProjectComRecords { get; set; }
    }
}
