//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceRejectProject
    {
        public System.Guid Id { get; set; }
        public string RegNumber { get; set; }
        public Nullable<System.Guid> RejectReasonDicId { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public Nullable<int> RegisterDfId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
