//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceProjectJournal
    {
        public System.Guid Id { get; set; }
        public int Type { get; set; }
        public string Number { get; set; }
        public string OutgoingNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> OutgoingDate { get; set; }
        public int Status { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.Guid ManufacturerOrganizationId { get; set; }
        public System.Guid HolderOrganizationId { get; set; }
        public System.Guid ProxyOrganizationId { get; set; }
        public string DoverennostNumber { get; set; }
        public Nullable<System.DateTime> DoverennostCreatedDate { get; set; }
        public Nullable<System.DateTime> DoverennostExpiryDate { get; set; }
        public string Filial { get; set; }
        public string NameKz { get; set; }
        public string NameRu { get; set; }
        public string RegNumber { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.Guid> LsTypeDicId { get; set; }
        public string NameOriginal { get; set; }
        public string MnnRu { get; set; }
        public string MnnEn { get; set; }
        public string FormNameKz { get; set; }
        public string FormNameRu { get; set; }
        public string Dosage { get; set; }
        public string CountPackage { get; set; }
        public string Concentration { get; set; }
        public string CodeAtx { get; set; }
        public Nullable<System.Guid> IntroducingMethodDicId { get; set; }
        public bool IsConvention { get; set; }
        public Nullable<System.Guid> ImnSecuryTypeDicId { get; set; }
        public Nullable<System.Guid> RePriceDicId { get; set; }
        public Nullable<System.Guid> ResultTypeDicId { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ContrDate { get; set; }
        public Nullable<System.DateTime> ConclusionDate { get; set; }
        public Nullable<bool> IsStageExpired { get; set; }
        public Nullable<int> ExpiredDayCount { get; set; }
        public string ExpertAz { get; set; }
        public string OutgoingDoc { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<bool> IsNewManufacrurer { get; set; }
        public string ManufacturerOrgName { get; set; }
        public string ApplicantOrgName { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.Guid> ListTypeDicId { get; set; }
        public Nullable<int> MnnOrderNumber { get; set; }
        public string RePriceName { get; set; }
        public string ListTypeName { get; set; }
        public string TypeValue { get; set; }
        public string StatusValue { get; set; }
        public Nullable<System.Guid> PriceProjectId { get; set; }
        public Nullable<int> LeftDays { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> PassedDays { get; set; }
        public bool IsSigned { get; set; }
    }
}
