//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsView
    {
        public System.Guid Id { get; set; }
        public int Type { get; set; }
        public string TypeValue { get; set; }
        public string Number { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
        public string StausValue { get; set; }
        public string NameRu { get; set; }
        public Nullable<bool> IsRegisterProject { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.DateTime> OutgoingDate { get; set; }
        public string info { get; set; }
    }
}
