//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrtPrjsView2
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<System.DateTime> ProjectDate { get; set; }
        public string ManufaturerName { get; set; }
        public string CountryName { get; set; }
        public string ApplicantName { get; set; }
        public string ProtocolNumber { get; set; }
        public Nullable<System.DateTime> ProtocolDate { get; set; }
        public string ProtocolSummary { get; set; }
        public string ResultDictionaryId { get; set; }
        public Nullable<System.Guid> ProtocolId { get; set; }
        public string Name { get; set; }
    }
}
