//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReesrtObk
    {
        public long id { get; set; }
        public string name { get; set; }
        public string producer_name { get; set; }
        public string country_name { get; set; }
        public string tnved_code { get; set; }
        public string kpved_code { get; set; }
        public string register_nd { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string currency_name { get; set; }
        public Nullable<decimal> costExch { get; set; }
        public Nullable<long> register_id { get; set; }
        public Nullable<long> drug_form_id { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
    }
}
