//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Knfs
    {
        public string Code { get; set; }
        public string GroupFarm { get; set; }
        public string Name { get; set; }
        public string Form { get; set; }
        public string Number { get; set; }
        public decimal Cost { get; set; }
        public System.Guid Id { get; set; }
        public string Characteristic { get; set; }
        public string Measure { get; set; }
        public string Tn { get; set; }
        public Nullable<System.DateTime> DateExpiry { get; set; }
        public string Dosage { get; set; }
        public decimal CostTn { get; set; }
        public int State { get; set; }
        public int Type { get; set; }
    }
}
