//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_PurchasePrices
    {
        public long Id { get; set; }
        public string SKP { get; set; }
        public string Name { get; set; }
        public string TradeName { get; set; }
        public string DosageForm { get; set; }
        public string Unit { get; set; }
        public Nullable<float> Packing { get; set; }
        public string Producer { get; set; }
        public Nullable<float> Price { get; set; }
    }
}
