//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Limits
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string GroupFarm { get; set; }
        public string Name { get; set; }
        public string Form { get; set; }
        public string Number { get; set; }
        public decimal Cost { get; set; }
    }
}
