//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterOrdererView
    {
        public int ReestrId { get; set; }
        public string MnnName { get; set; }
        public string Characteristic { get; set; }
        public string DrugForm { get; set; }
        public string Concentration { get; set; }
        public string Dosage { get; set; }
        public string TradeName { get; set; }
        public string RegNumber { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> RegDateExpire { get; set; }
        public string AtxCode { get; set; }
        public string Manufacturer { get; set; }
        public string Measure { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> substance_count { get; set; }
        public Nullable<int> unit_count { get; set; }
        public Nullable<decimal> volume { get; set; }
        public string dosage_comment { get; set; }
    }
}
