//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterOrderer2Views
    {
        public Nullable<int> IntId { get; set; }
        public Nullable<System.Guid> Id { get; set; }
        public int regId { get; set; }
        public string C_int_name { get; set; }
        public string substance { get; set; }
        public string volume { get; set; }
        public string dosage_comment { get; set; }
        public string name { get; set; }
        public string C_dosage_form_name { get; set; }
        public string concentration { get; set; }
        public string reg_number { get; set; }
        public string C_producer_name { get; set; }
        public string C_country_name { get; set; }
        public string C_atc_code { get; set; }
        public string dosage_value { get; set; }
        public string um { get; set; }
        public string box_name1 { get; set; }
        public string box_name2 { get; set; }
        public string box_count { get; set; }
        public Nullable<int> dfId { get; set; }
    }
}
