//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string Text { get; set; }
        public string AnswersId { get; set; }
        public string AnswersValue { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public string ModifiedUser { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> PageCount { get; set; }
        public Nullable<int> SymbolCount { get; set; }
        public string TitleDicId { get; set; }
        public string TitleDicValue { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Task Task { get; set; }
    }
}
