//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestOrder
    {
        public RequestOrder()
        {
            this.RequestLists = new HashSet<RequestList>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int OrderType { get; set; }
        public int OrderYear { get; set; }
        public string OrderNumber { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<RequestList> RequestLists { get; set; }
    }
}
