//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public System.Guid Id { get; set; }
        public string UniqueName { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public int Rank { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    }
}
