//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_atc_codes
    {
        public sr_atc_codes()
        {
            this.EXP_DrugDeclaration = new HashSet<EXP_DrugDeclaration>();
            this.sr_atc_codes1 = new HashSet<sr_atc_codes>();
            this.sr_register_drugs = new HashSet<sr_register_drugs>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string name_kz { get; set; }
        public Nullable<int> parent_id { get; set; }
        public bool block_sign { get; set; }
    
        public virtual ICollection<EXP_DrugDeclaration> EXP_DrugDeclaration { get; set; }
        public virtual ICollection<sr_atc_codes> sr_atc_codes1 { get; set; }
        public virtual sr_atc_codes sr_atc_codes2 { get; set; }
        public virtual ICollection<sr_register_drugs> sr_register_drugs { get; set; }
    }
}
