//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_boxes
    {
        public sr_boxes()
        {
            this.EXP_DrugWrapping = new HashSet<EXP_DrugWrapping>();
            this.sr_boxes1 = new HashSet<sr_boxes>();
            this.sr_register_boxes = new HashSet<sr_register_boxes>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string name_kz { get; set; }
        public Nullable<int> parent_id { get; set; }
        public bool block_sign { get; set; }
    
        public virtual ICollection<EXP_DrugWrapping> EXP_DrugWrapping { get; set; }
        public virtual ICollection<sr_boxes> sr_boxes1 { get; set; }
        public virtual sr_boxes sr_boxes2 { get; set; }
        public virtual ICollection<sr_register_boxes> sr_register_boxes { get; set; }
    }
}
