//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_degree_risks
    {
        public sr_degree_risks()
        {
            this.sr_degree_risk_details = new HashSet<sr_degree_risk_details>();
            this.sr_register_mt = new HashSet<sr_register_mt>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string name_kz { get; set; }
    
        public virtual ICollection<sr_degree_risk_details> sr_degree_risk_details { get; set; }
        public virtual ICollection<sr_register_mt> sr_register_mt { get; set; }
    }
}
