//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_drug_forms
    {
        public sr_drug_forms()
        {
            this.EXP_DrugDeclaration = new HashSet<EXP_DrugDeclaration>();
        }
    
        public int id { get; set; }
        public int register_id { get; set; }
        public Nullable<int> pr_box_id { get; set; }
        public Nullable<int> sec_box_id { get; set; }
        public string box_count { get; set; }
        public string full_name { get; set; }
        public string specification { get; set; }
        public string full_name_kz { get; set; }
        public Nullable<bool> complete_sign { get; set; }
        public Nullable<int> user_id { get; set; }
        public string pr_box_count { get; set; }
        public string sec_box_count { get; set; }
        public Nullable<int> inter_box_id { get; set; }
        public string inter_box_count { get; set; }
    
        public virtual ICollection<EXP_DrugDeclaration> EXP_DrugDeclaration { get; set; }
        public virtual sr_register sr_register { get; set; }
        public virtual sr_register_boxes sr_register_boxes { get; set; }
        public virtual sr_register_boxes sr_register_boxes1 { get; set; }
    }
}
