//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_international_names
    {
        public sr_international_names()
        {
            this.EXP_DrugDeclaration = new HashSet<EXP_DrugDeclaration>();
            this.sr_register_drugs = new HashSet<sr_register_drugs>();
        }
    
        public int id { get; set; }
        public string name_rus { get; set; }
        public string name_eng { get; set; }
        public string name_lat { get; set; }
        public string name_kz { get; set; }
        public bool block_sign { get; set; }
        public bool new_sign { get; set; }
    
        public virtual ICollection<EXP_DrugDeclaration> EXP_DrugDeclaration { get; set; }
        public virtual ICollection<sr_register_drugs> sr_register_drugs { get; set; }
    }
}
