//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_mt_categories
    {
        public sr_mt_categories()
        {
            this.sr_mt_categories1 = new HashSet<sr_mt_categories>();
            this.sr_register_mt = new HashSet<sr_register_mt>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string name_kz { get; set; }
        public Nullable<int> parent_id { get; set; }
    
        public virtual ICollection<sr_mt_categories> sr_mt_categories1 { get; set; }
        public virtual sr_mt_categories sr_mt_categories2 { get; set; }
        public virtual ICollection<sr_register_mt> sr_register_mt { get; set; }
    }
}
