//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_pharmacological_actions
    {
        public sr_pharmacological_actions()
        {
            this.sr_pharmacological_actions1 = new HashSet<sr_pharmacological_actions>();
            this.sr_register_pharmacological_actions = new HashSet<sr_register_pharmacological_actions>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string name_kz { get; set; }
        public Nullable<int> parent_id { get; set; }
        public bool block_sign { get; set; }
    
        public virtual ICollection<sr_pharmacological_actions> sr_pharmacological_actions1 { get; set; }
        public virtual sr_pharmacological_actions sr_pharmacological_actions2 { get; set; }
        public virtual ICollection<sr_register_pharmacological_actions> sr_register_pharmacological_actions { get; set; }
    }
}
