//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_producer_types
    {
        public sr_producer_types()
        {
            this.sr_register_producers = new HashSet<sr_register_producers>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string name_kz { get; set; }
    
        public virtual ICollection<sr_register_producers> sr_register_producers { get; set; }
    }
}
