//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_producers
    {
        public sr_producers()
        {
            this.sr_register_mt_parts = new HashSet<sr_register_mt_parts>();
            this.sr_register_producers = new HashSet<sr_register_producers>();
        }
    
        public int id { get; set; }
        public Nullable<long> form_type_id { get; set; }
        public string name { get; set; }
        public string name_kz { get; set; }
        public string name_eng { get; set; }
        public string rnn { get; set; }
        public string bin { get; set; }
        public string iin { get; set; }
        public int type_id { get; set; }
        public bool block_sign { get; set; }
    
        public virtual ICollection<sr_register_mt_parts> sr_register_mt_parts { get; set; }
        public virtual ICollection<sr_register_producers> sr_register_producers { get; set; }
    }
}
