//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_register_names
    {
        public long id { get; set; }
        public int register_id { get; set; }
        public string name { get; set; }
        public string name_kz { get; set; }
        public string name_eng { get; set; }
        public long country_id { get; set; }
    
        public virtual sr_countries sr_countries { get; set; }
        public virtual sr_register sr_register { get; set; }
    }
}
