//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_register_instructions_files
    {
        public int id { get; set; }
        public byte[] file_kaz { get; set; }
        public byte[] file_rus { get; set; }
        public string file_ext_kz { get; set; }
        public string file_ext { get; set; }
    
        public virtual sr_register_instructions sr_register_instructions { get; set; }
    }
}
