//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_register_drugs
    {
        public sr_register_drugs()
        {
            this.sr_register_use_methods = new HashSet<sr_register_use_methods>();
        }
    
        public int id { get; set; }
        public int drug_type_id { get; set; }
        public int int_name_id { get; set; }
        public string C_int_name { get; set; }
        public int atc_id { get; set; }
        public string C_atc_code { get; set; }
        public string C_atc_name { get; set; }
        public int dosage_form_id { get; set; }
        public string dosage_comment { get; set; }
        public string dosage_comment_kz { get; set; }
        public string C_dosage_form_name { get; set; }
        public Nullable<decimal> dosage_value { get; set; }
        public Nullable<long> dosage_measure_id { get; set; }
        public string C_dosage { get; set; }
        public string concentration { get; set; }
        public string concentration_kz { get; set; }
        public string C_unit_count { get; set; }
        public bool recipe_sign { get; set; }
        public bool generic_sign { get; set; }
        public int life_type_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string category_pos { get; set; }
        public Nullable<int> nd_name_id { get; set; }
        public string nd_name { get; set; }
        public string nd_number { get; set; }
        public string nd_comment { get; set; }
        public string substance { get; set; }
        public bool biosimilar_sign { get; set; }
        public bool auto_generic_sign { get; set; }
        public bool orphan_sign { get; set; }
    
        public virtual sr_atc_codes sr_atc_codes { get; set; }
        public virtual sr_categories sr_categories { get; set; }
        public virtual sr_dosage_forms sr_dosage_forms { get; set; }
        public virtual sr_international_names sr_international_names { get; set; }
        public virtual sr_measures sr_measures { get; set; }
        public virtual ICollection<sr_register_use_methods> sr_register_use_methods { get; set; }
    }
}
