//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_register_boxes
    {
        public sr_register_boxes()
        {
            this.sr_drug_forms = new HashSet<sr_drug_forms>();
            this.sr_drug_forms1 = new HashSet<sr_drug_forms>();
        }
    
        public int id { get; set; }
        public int register_id { get; set; }
        public int box_id { get; set; }
        public Nullable<bool> inner_sign { get; set; }
        public Nullable<decimal> volume { get; set; }
        public Nullable<long> volume_measure_id { get; set; }
        public int unit_count { get; set; }
        public string box_size { get; set; }
        public string description { get; set; }
    
        public virtual sr_boxes sr_boxes { get; set; }
        public virtual ICollection<sr_drug_forms> sr_drug_forms { get; set; }
        public virtual ICollection<sr_drug_forms> sr_drug_forms1 { get; set; }
        public virtual sr_register sr_register { get; set; }
    }
}
