//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_register_instructions
    {
        public int id { get; set; }
        public int register_id { get; set; }
        public int instruction_type_id { get; set; }
        public string comment { get; set; }
    
        public virtual sr_instruction_types sr_instruction_types { get; set; }
        public virtual sr_register sr_register { get; set; }
        public virtual sr_register_instructions_files sr_register_instructions_files { get; set; }
    }
}
