//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_register_boxes_rk_ls
    {
        public int id { get; set; }
        public Nullable<bool> state_sign { get; set; }
        public Nullable<System.DateTime> state_date { get; set; }
    
        public virtual sr_register_boxes sr_register_boxes { get; set; }
    }
}
