//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_register_mt
    {
        public sr_register_mt()
        {
            this.sr_register_mt_parts = new HashSet<sr_register_mt_parts>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public string purpose { get; set; }
        public string use_area { get; set; }
        public int mt_category_id { get; set; }
        public int degree_risk_id { get; set; }
        public int risk_detail_id { get; set; }
        public bool mt_sign { get; set; }
        public bool sterility_sign { get; set; }
        public bool measurement_sign { get; set; }
        public bool balk_sign { get; set; }
    
        public virtual sr_degree_risk_details sr_degree_risk_details { get; set; }
        public virtual sr_degree_risks sr_degree_risks { get; set; }
        public virtual sr_mt_categories sr_mt_categories { get; set; }
        public virtual sr_register sr_register { get; set; }
        public virtual ICollection<sr_register_mt_parts> sr_register_mt_parts { get; set; }
        public virtual sr_register_mt_kz sr_register_mt_kz { get; set; }
    }
}
