//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrProducerView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string NameKz { get; set; }
        public Nullable<long> FormTypeId { get; set; }
        public string FormTypeFullName { get; set; }
        public string FormTypeFullNameKz { get; set; }
        public string FormTypeName { get; set; }
        public string FormTypeNameKz { get; set; }
    }
}
