//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.AccessTasks = new HashSet<AccessTask>();
            this.Reports = new HashSet<Report>();
        }
    
        public System.Guid Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AuthorId { get; set; }
        public string AuthorValue { get; set; }
        public string ExecutorId { get; set; }
        public string ExecutorValue { get; set; }
        public int State { get; set; }
        public string DocumentValue { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public Nullable<System.Guid> ActivityId { get; set; }
        public Nullable<System.DateTime> AutoExecutionDate { get; set; }
        public string Number { get; set; }
        public int FunctionType { get; set; }
        public bool IsActive { get; set; }
        public int NotificationCount { get; set; }
        public bool IsNotification { get; set; }
        public int SortingNumber { get; set; }
        public Nullable<System.DateTime> DateOfOperation { get; set; }
        public string ModifiedUser { get; set; }
        public bool IsMainLine { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int TypeEx { get; set; }
        public int Stage { get; set; }
    
        public virtual ICollection<AccessTask> AccessTasks { get; set; }
        public virtual Activity Activity { get; set; }
        public virtual Document Document { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}
