//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTmc
    {
        public long Id { get; set; }
        public string Number { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Count { get; set; }
        public string CountFact { get; set; }
        public string Unit { get; set; }
    }
}
