//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public byte[] Data { get; set; }
        public Nullable<int> TemplateType { get; set; }
        public byte[] Report { get; set; }
        public Nullable<System.Guid> ConvertDictionaryTypeId { get; set; }
        public Nullable<int> ConvertType { get; set; }
        public string DictionaryTypeValue { get; set; }
        public string DictionaryTypeId { get; set; }
        public string Value { get; set; }
        public string Validation { get; set; }
        public byte[] PrintForm { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
    }
}
