//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmcApplicationComment
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Comment { get; set; }
        public System.Guid ApplicationId { get; set; }
        public System.Guid CreateEmployeeId { get; set; }
    }
}
