//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmcOutView
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedEmployeeId { get; set; }
        public string CreatedEmployeeValue { get; set; }
        public int StateType { get; set; }
        public string StateTypeValue { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> OutTypeDicId { get; set; }
        public string OutTypeDicValue { get; set; }
        public Nullable<System.Guid> StorageDicId { get; set; }
        public string StorageDicValue { get; set; }
        public string Safe { get; set; }
        public string Rack { get; set; }
        public Nullable<System.Guid> OwnerEmployeeId { get; set; }
        public string OwnerEmployeeValue { get; set; }
    }
}
