//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmcOutCountView
    {
        public Nullable<decimal> CountActual { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid TmcOutId { get; set; }
        public System.Guid TmcId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> MeasureTypeConvertDicId { get; set; }
        public string MeasureTypeConvertDicValue { get; set; }
        public decimal Count { get; set; }
        public decimal CountFact { get; set; }
        public int StateType { get; set; }
        public string StateTypeValue { get; set; }
        public string Note { get; set; }
        public string OwnerEmployeeValue { get; set; }
        public string StorageDicValue { get; set; }
        public string Safe { get; set; }
        public string Rack { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedEmployeeId { get; set; }
        public Nullable<int> TmcStateType { get; set; }
        public Nullable<System.Guid> TmcInId { get; set; }
        public string Number { get; set; }
        public string Code { get; set; }
        public string Manufacturer { get; set; }
        public string Serial { get; set; }
        public Nullable<decimal> TmcCount { get; set; }
        public Nullable<System.Guid> MeasureTypeDicId { get; set; }
        public Nullable<decimal> TmcCountFact { get; set; }
        public Nullable<decimal> CountConvert { get; set; }
        public Nullable<System.Guid> TmcMeasureTypeConvertDicId { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.Guid> PackageDicId { get; set; }
        public Nullable<System.Guid> TmcTypeDicId { get; set; }
        public Nullable<System.Guid> StorageDicId { get; set; }
        public string TmcSafe { get; set; }
        public string TmcRack { get; set; }
        public Nullable<System.Guid> OwnerEmployeeId { get; set; }
        public string MeasureTypeDicValue { get; set; }
        public string PackageDicValue { get; set; }
        public string TmcTypeDicValue { get; set; }
        public string OwnerEmployeeName { get; set; }
        public Nullable<int> ApplicationStateType { get; set; }
    }
}
