//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmcOffView
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedEmployeeId { get; set; }
        public string CreatedEmployeeValue { get; set; }
        public int StateType { get; set; }
        public Nullable<System.Guid> TmcOutId { get; set; }
        public string Note { get; set; }
        public decimal Count { get; set; }
        public string StateTypeValue { get; set; }
        public Nullable<System.Guid> ExpertiseStatementId { get; set; }
        public string ExpertiseStatementNumber { get; set; }
    }
}
