//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmcReport
    {
        public TmcReport()
        {
            this.TmcReportTasks = new HashSet<TmcReportTask>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.DateTime PeriodStartDate { get; set; }
        public System.DateTime PeriodEndDate { get; set; }
        public System.Guid DepartmentId { get; set; }
        public string DepartmentValue { get; set; }
        public System.Guid CreateEmployeeId { get; set; }
        public string CreateEmployeeValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string ReportType { get; set; }
    
        public virtual ICollection<TmcReportTask> TmcReportTasks { get; set; }
    }
}
