//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsAddress
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid UnitsId { get; set; }
        public System.Guid RegionId { get; set; }
        public string AddressNameRu { get; set; }
        public string AddressNameKz { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
