//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitsView
    {
        public int VisitId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public int VisitDuration { get; set; }
        public int VisitTimeBegin { get; set; }
        public string VisitComment { get; set; }
        public int VisitStatusId { get; set; }
        public string VisitStatusName { get; set; }
        public int VisitTypeId { get; set; }
        public string VisitTypeName { get; set; }
        public string VisitTypeGroup { get; set; }
        public System.Guid VisitorId { get; set; }
        public string VisitorLastName { get; set; }
        public string VisitorFirstName { get; set; }
        public string VisitorMiddleName { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeMiddleName { get; set; }
        public string VisitRatingComment { get; set; }
        public Nullable<int> VisitRatingValue { get; set; }
    }
}
