//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Id { get; set; }
        public int VisitTypeId { get; set; }
        public System.Guid VisitorId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.DateTime Date { get; set; }
        public int TimeBegin { get; set; }
        public int Duration { get; set; }
        public string Comment { get; set; }
        public int VisitStatusId { get; set; }
        public Nullable<int> RatingValue { get; set; }
        public string RatingComment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual VisitStatus VisitStatus { get; set; }
        public virtual VisitType VisitType { get; set; }
    }
}
